### ISSUE TITLE
Different 3D shapes in the preview

### ISSUE THREAD

**Issue by Hevedy** [kmkolasinski/AwesomeBump#10]
Why no add different shapes in the 3D preview of the textures ?  
If you need shapes: https://github.com/Hevedy/PurpleprintKit/tree/master/Content/3D/Geometry/Simple

**Comment by kmkolasinski** [comment]
Shapes are not the biggest problem :) We must first integrate (or write) some model importer into the Qt code. The feature of reading OBJ models into the program is in future plans. I was thinking about assimp but it could be something much simpler. Do you know some model importer library which is OS independent?

**Comment by Hevedy** [comment]
Don't have Qt an function ? http://qt-project.org/wiki/Loading-a-3D-Model anyway you have the http://assimp.sourceforge.net/ now I do not remember more, sorry.
But the Qt OpenGL don't is independent of OS ?

**Comment by kmkolasinski** [comment]
Hi,
Qt claims himself to be cross platform, but actually it occured that if something works well on Win it can crash on Linux. The biggest problem is OSX for now. We want to make one code for all platforms. But we still have to deal with many problems.
 
Qt3D is separate package which requires to be installed intependently from github resources. This library includes assimp. Unfortunatelly, I have allready wasted few hours to make it worked in AB, maybe I did something wrong or maybe it is not soo easy to do... That is why I prefer to write OBJ loader from scratch which is super simply than trying to figure out how to make the Qt3D works togheter with AB :/

**Comment by kmkolasinski** [comment]
Added support for 3D models.
