### ISSUE TITLE
Build issues on WIN10 with AB V5.0

### ISSUE THREAD

**Issue by Iraito** [kmkolasinski/AwesomeBump#100]
This is the issues i get **: error: QtnProperty not found. Did you forget to 'git submodule init/update'**

**Comment by kmkolasinski** [comment]
Do you use git to clone repository or just downloaded zip file ?
1. if not you have to download the [QtnProperty](https://github.com/kmkolasinski/QtnProperty) subproject and paste its content to the Source/utils/QtnProperty folder. 
2. Then you have to build it. It is standard QtCreator project. 
3. Then you can open AB project and try to compile it. This should help


PS: Current version for Win has some strange bug which we have to fix.

**Comment by kmkolasinski** [comment]
I have uploaded binary package for Windows version.

**Comment by kmkolasinski** [comment]
@Iraito did you solved your problem?

**Comment by Iraito** [comment]
Yes, sorry for not answering, on windows everything is working fine, i didn't try again on linux since most of my work is on windows in this period.

**Comment by kmkolasinski** [comment]
Ok, no problem thanks for answer. I'm closing this issue.
