### ISSUE TITLE
'setDefaultFormat' is not a member of 'QSurfaceFormat'

### ISSUE THREAD

**Issue by jeje232** [kmkolasinski/AwesomeBump#101]
Hi,
I have problem when I try to build AwesomBump.

../AwesomeBump-Linuxv5.0/Sources/main.cpp:285: error: 'setDefaultFormat' is not a member of 'QSurfaceFormat'
     QSurfaceFormat::setDefaultFormat(format);

I try with
Qt Creator 4.0.2
Based on Qt 5.7.0 (GCC 4.9.1 20140922 (Red Hat 4.9.1-10), 64 bit)
Built on Jun 13 2016 01:05:36

Qt Creator 3.2.1
Based on Qt 5.3.2 (GCC 4.9.2, 64 bit)
Built on May 10 2016 at 17:53:15

My system it's debian Jessie.

Thanks,

Jeremy

**Comment by ppiecuch** [comment]
Hi, I have added #include <QSurfaceFormat> in main.cpp, but this rather looks like some Qt module is missing.

Regards
P.

**Comment by kmkolasinski** [comment]
The binary package is not working on your system?
