### ISSUE TITLE
U.I. Hang

### ISSUE THREAD

**Issue by EriicM** [kmkolasinski/AwesomeBump#102]
I've isolated an issue that causes the u.i. to hang at start up. I found it was caused by the sky_cube_env.obj....once this was removed the program started perfectly.

Amd A4-4300M APU Laptop

**Comment by kmkolasinski** [comment]
Hi thanks for info, which version of AB caused that problem?

**Comment by EriicM** [comment]
For me it seems to be all versions after 2.1 i tried them all before finding the problem.

**Comment by iarga** [comment]
Thank you EriicM, I had exactly the same problem. After I removed sky_cube_env.obj , the problem was gone. Also this problem existed from versions after 2.1.

ATI Radeon HD 5400 series

I made a Github account specialy to confirm this bug. Again Thanks for finding a solution.

**Comment by EriicM** [comment]
Glad to have helped the issue
