### ISSUE TITLE
Fallout 4 textures

### ISSUE THREAD

**Issue by Gernash** [kmkolasinski/AwesomeBump#103]
I've been playing with AwsomeBump and as a Normal Map generator, it's well, Awesome. Lots of control.

BTW I'm new to all this.
The generator seems to make specific maps for 3D modeling application. I've been using the:
Normals
Specular
Roughness
and Metalic (not much of this as playing with terrain)

Is there any information anywhere how to properly use these generated files in regards to games that use 72dpi and how to blend them to get the best effect with bump and height mapping?

Have you ever considered to make a more specific application/Option to generate files particular games like Skyrim and Fallout 4 (These are the ones I'm interested in and have a large community). 

Main thing Other than that is how to set up the 3D render shader to more closely emulate how it looks in-Game as I'm having to play with the outputted files alot to get the right balance with the specular maps.

Also is there a FORUM that Awsomebump community chat in? So I can get assistance with normal and Specular Map generation?

Thanks in advance.

**Comment by kmkolasinski** [comment]
Hi, there is no designated forum, but you can try at blenderartist,  which covers a lot of topics with many experts. AB is a simple image generator, the final render depends on the graphics engine you use. Since 5.0 you can tune the 3D render, but you have to know how to code in GLSL.

**Comment by Gernash** [comment]
OK. I'll look into that. FO4 uses the maps in odd ways but I'm getting away with it for now. I'll try blend artists and see if they might point me in the direction I'm looking for thankyou.
