### ISSUE TITLE
Shutdown when converting images

### ISSUE THREAD

**Issue by Tywele** [kmkolasinski/AwesomeBump#104]
As soon as I hit the convert button to generate all the maps from the currently loaded image my computer shuts down completely as if the power was cut off and restarts itself immediately after.

This is the only program where this is happening.

I'm using Windows 10 with an i7 3770K and a GTX 980. Temperatures are in check and everything else also. This also happended with previous versions of the software. I had hopes that with the new release this would be fixed. Unfortunately this is not the case. I hope this can be fixed somehow.

[log.txt](https://github.com/kmkolasinski/AwesomeBump/files/443518/log.txt)

**Comment by kmkolasinski** [comment]
Hi this is a very unique error, I haven't seen such things before. Few questions:
1. Could you try with smaller images ? The 2592x3888 is quite big and it may freeze system. 
2. Did you try to build the source code by yourself or use the binary packages?

**Comment by Tywele** [comment]
1. I can try that yes
2. I used the prebuilt package

**Comment by kmkolasinski** [comment]
2. I'm not sure if AB works fine on Win10 there may be some changes in Qt libraries hence the problems. At least I can guide you how to build AB from source code.

**Comment by Tywele** [comment]
Ok, I tried a 1024x1024 texture and that seemed to have worked. It seems like AwesomeBump is not able to handle high res textures properly.

**Comment by kmkolasinski** [comment]
I think that this is system related problem. Can you check this [link](https://support.allegorithmic.com/documentation/display/SPDOC/GPU+drivers+crash+with+long+computations) and give me a feedback ?
