### ISSUE TITLE
normals to heightmap in 5.0 missing option?

### ISSUE THREAD

**Issue by TurBoss** [kmkolasinski/AwesomeBump#106]
as i can see here : https://www.youtube.com/watch?v=MTR7u_FMhFU
there was a function to calculate heightmaps from bumps

but I can't find this option on the 5.0 version

thx

**Comment by kmkolasinski** [comment]
Hmmm, there is something which does similar stuff. It is called: "Recalculate from normal (output)".  Does not it work for you ?

**Comment by TurBoss** [comment]
omg I don't know how i can miss that xD

it works thank you!
