### ISSUE TITLE
cmake build issues on linux (kde neon/ubuntu 16)

### ISSUE THREAD

**Issue by CapsAdmin** [kmkolasinski/AwesomeBump#109]
CMakeLists.txt in root tries to find LINUX but there's no such variable. (did you mean UNIX?) I can work around this with -DLINUX=1. I'm using cmake version 3.5.1.

When I attempt to make I get:
`/home/caps/AwesomeBump/Sources/utils/QtnProperty/Core/PropertyBase.cpp:19:34: fatal error: QtScript/QScriptEngine: No such file or directory`

I had to install `qtscript5-dev`. I already had `qtbase5-dev` installed.

Now there's some include path issues with QtnProperty.

In `PropertyWidget/Utils/AccessibilityProxy.h` I had to change:
```
#include "PropertyWidgetAPI.h"
#include "../Core/PropertySet.h"
```
to
```
#include "../PropertyWidgetAPI.h"
#include "../../Core/PropertySet.h"
```
And in `PropertyWidget/Delegates∕PropertyDelegateAux.cpp` I had to change
`#include "PropertyView.h"`
to 
`#include "../PropertyView.h"`

Then I get link errors which I'm not sure how to solve. https://gist.github.com/CapsAdmin/b75f183caf17314611f5ae895a11a59d

**Comment by kmkolasinski** [comment]
Hi @CapsAdmin,
   Do you need to use cmake? There is a stand alone script written in bash, which can do the same and it is testes on recent version.

**Comment by CapsAdmin** [comment]
I don't really need to use cmake but I thought it was worth mentioning anyway.

I never got unixBuildScript.sh to work because I never understood which path I should set MY_QT_PATH to. Looking at the comment above it I tried to locate "gcc_64" but I found nothing.

However skipping the MY_QT_PATH path and just manually running the below works fine.
```
git clone https://github.com/kmkolasinski/AwesomeBump
cd AwesomeBump
git submodule init
git submodule update
qmake
make
cp -vr workdir/`cat workdir/current`/bin/AwesomeBump$exe ./Bin
```

**Comment by kmkolasinski** [comment]
cmake script is actually not mine, that is why I don't know if it is not working, but thanks for reporting this.
Regarding the unixBuildScript.sh, I always install QtCreator manually so I know what
is the correct install path, however if you have ubuntu you may use default Qt
libraries with default paths that is why it worked for you without specifying  MY_QT_PATH.
BTW: Why don't you use prebuild binary packages ?
