### ISSUE TITLE
Fragment shader uses reserved word as var name

### ISSUE THREAD

**Issue by LinusVanElswijk** [kmkolasinski/AwesomeBump#11]
The fragment shader contains a variable named "output", but "output" is one of the reserved word in GLSL.
(https://www.opengl.org/registry/doc/GLSLangSpec.4.00.8.clean.pdf page 15)

The result is that the areas that would normally contain the textures are rendered as pure black.
The following error shows up in the log file:

[04/02/2015 10:10:39] {Warning} 	 QOpenGLShader::compile(Fragment): Fragment shader failed to compile with the following errors:
ERROR: 2:688: error(#133) Reserved word: output
ERROR: 2:688: error(#132) Syntax error: "output" parse error
ERROR: error(#273) 2 compilation errors.  No code generated

**Comment by kmkolasinski** [comment]
Hi, thank you. I will fix it today.

**Comment by LinusVanElswijk** [comment]
Hey, I already made a pull request that should fix this :)

**Comment by kmkolasinski** [comment]
Nice, thank you :) I will take a look on it this evening.
