### ISSUE TITLE
Can't build on mac via unixBuildScript.sh

### ISSUE THREAD

**Issue by finscn** [kmkolasinski/AwesomeBump#111]
the console log :
```
QtnProperty module is already initialized. No action is performed.
cd Sources/ && ( test -e Makefile || /usr/local/Cellar/qt5/5.7.1_1/bin/qmake /Users/rocky/DEV/@git-fav/AwesomeBump/Sources/Sources.pro -o Makefile ) && /Applications/Xcode.app/Contents/Developer/usr/bin/make -f Makefile 
/Users/rocky/DEV/@git-fav/AwesomeBump/Sources/utils/QtnProperty/bin-osx/QtnPEG properties/Filter3DDOF.pef
dyld: Library not loaded: @rpath/QtCore.framework/Versions/5/QtCore
  Referenced from: /Users/rocky/DEV/@git-fav/AwesomeBump/Sources/utils/QtnProperty/bin-osx/QtnPEG
  Reason: image not found
make[1]: *** [properties/Filter3DDOF.peg.cpp] Abort trap: 6
make: *** [sub-Sources-make_first-ordered] Error 2
```

What can I do for it ?

macOS 10.12
qt 5.7.1.1 ( install via brew)

**Comment by kmkolasinski** [comment]
Hi,
I have no experience with building AB on macOS, however the message says that your are lack in  libraries or you must provide path to that library. See for example this link:
http://stackoverflow.com/questions/13611740/qt-mac-osx-10-8-dyld-library-not-loaded-image-not-found

It seems that you have not installed Qt on your system: @rpath/QtCore.framework/Versions/5/QtCore

**Comment by finscn** [comment]
@kmkolasinski , I've installed QT5.

Now,  I install qt from official homepage, and build AB use QT creator , I got the same error message.  tears...

And the second question : 
I run  AB bin  on windows, but it tells me my video card doesn't support OpenGL 3.3 .
Could I run it with OpenGL 2.0 only ?

**Comment by finscn** [comment]
@kmkolasinski  , I replace the `AwesomeBump/Sources/utils/QtnProperty/bin-osx/QtnPEG`  with the new version at  https://github.com/lexxmark/QtnProperty/blob/master/bin-osx/QtnPEG .
Now it could be Build and Install.

But in app , I can't see the Full UI  and can't resize the tool bars :

<img width="1117" alt="2017-01-18 6 50 56" src="https://cloud.githubusercontent.com/assets/288367/22061377/a9ce3b0e-ddaf-11e6-9325-8b6b8185a797.png">

**Comment by ppiecuch** [comment]
Good to know that PEG is working - I have notices that QtnProperty has been updated recently. I have a few changes to OS X build locally but I will finish these next month.

Regards
P.

**Comment by finscn** [comment]
@ppiecuch  @kmkolasinski  , in mac OS , the preview zone always black.  Whatever I open what file .

**Comment by kmkolasinski** [comment]
Please send us the log.txt file.

**Comment by finscn** [comment]
@kmkolasinski  where is ` log.txt` ?

**Comment by kmkolasinski** [comment]
It should it in the Bin folder.

**Comment by finscn** [comment]
I can't find it .

**Comment by kmkolasinski** [comment]
Then it should be in the folder where you start AwesomeBump application.

**Comment by finscn** [comment]
@kmkolasinski  I've found everywhere  , not found

**Comment by shayneoAtNorwood** [comment]
This isn't really resolved :( I've had the same problem put the ~/Qt/yadayada/clangsomething/bin in the script and it falls on its head on;-

cd Sources/ && ( test -e Makefile || /Users/shayneoneill/Qt/5.7/clang_64/bin/qmake /Users/shayneoneill/AwesomeBump/Sources/Sources.pro -o Makefile ) && /Applications/Xcode.app/Contents/Developer/usr/bin/make -f Makefile 
/Users/shayneoneill/AwesomeBump/Sources/utils/QtnProperty/bin-osx/QtnPEG properties/Filter3DDOF.pef
dyld: Library not loaded: @rpath/QtCore.framework/Versions/5/QtCore

Tried the replacing QtnPEG switcheroo, still no joy.

**Comment by brian-bates** [comment]
I'm experiencing the exact same issue on the most recent [commit](https://github.com/kmkolasinski/AwesomeBump/commit/bf4102421e9c0775401a0065ac0f0b16d5bffcab):
```
cd Sources/ && ( test -e Makefile || /usr/local/opt/qt/bin/qmake -o Makefile /Users/brian/workspace/AwesomeBump/Sources/Sources.pro ) && /Applications/Xcode.app/Contents/Developer/usr/bin/make -f Makefile
Project MESSAGE: *** Adding 'qtnproperty' module.
/Users/brian/workspace/AwesomeBump/Sources/utils/QtnProperty/bin-osx/QtnPEG properties/Filter3DDOF.pef
dyld: Library not loaded: @rpath/QtCore.framework/Versions/5/QtCore
  Referenced from: /Users/brian/workspace/AwesomeBump/Sources/utils/QtnProperty/bin-osx/QtnPEG
  Reason: image not found
make[1]: *** [properties/Filter3DDOF.peg.cpp] Abort trap: 6
make: *** [sub-Sources-make_first-ordered] Error 2
```
Has anyone had any traction with this? The `QtnPEG` swap was a no-go.

@kmkolasinski , You were asking about the log file. I don't think it's getting created. Running `find . -name log.txt` on the root directory comes back empty handed. Is called something else?

**Comment by kmkolasinski** [comment]
The log.txt is generated by running program not during the compilation. I don't have access to mac software that is why I cannot maintain the compilation for that system. From the message you can see that:
```
dyld: Library not loaded: @rpath/QtCore.framework/Versions/5/QtCore
```
there is something wrong with your Qt installation i.e. library is not installed or you need to set proper path for it.
