### ISSUE TITLE
curvature mask

### ISSUE THREAD

**Issue by brothermechanic** [kmkolasinski/AwesomeBump#112]
Hello
Is it possible to release generation of curvature mask (dirt,decay)
from may be normal map or ao map?
It will be a super feature

**Comment by kmkolasinski** [comment]
Hi, it is really interesting question, but unfortunately I have stopped my contribution to AB, I don't have time for this.

**Comment by brothermechanic** [comment]
Sadly(((
Hope project don't die
Your software is one of a kind on linux

**Comment by kmkolasinski** [comment]
Closing inactive issue
