### ISSUE TITLE
mkdir: /workdir/-dgb-gl4/bin/AwesomeBump.app/Contents: Permission denied

### ISSUE THREAD

**Issue by endersaka** [kmkolasinski/AwesomeBump#114]
This is what i get if I try to compile using the UNIX shell script provided. Qt 5.8, Mac OS X Sierra.

```
$ sh unixBuildScript.sh
QtnProperty module is already initialized. No action is performed.
cd Sources/ && /Applications/Xcode.app/Contents/Developer/usr/bin/make -f Makefile 
mkdir: /workdir/-dgb-gl4/bin/AwesomeBump.app/Contents: Permission denied
make[1]: *** [/workdir/-dgb-gl4/bin/AwesomeBump.app/Contents/PkgInfo] Error 1
make: *** [sub-Sources-make_default-ordered] Error 2
```

**Comment by kmkolasinski** [comment]
It seems that you are trying to build AB in folder which requires root access. See error line:
```
 /workdir/-dgb-gl4/bin/AwesomeBump.app/Contents: Permission denied
```
It is recommended to build and use AB in path which does not require root permissions.

**Comment by endersaka** [comment]
Thanks,

though, actually, I did not configure it manually. The shell script decided to write to that directory by itself.

**Comment by kmkolasinski** [comment]
Have you manager to solve your problem ?

**Comment by endersaka** [comment]
No way :-/ ... Thanks for asking.

**Comment by Norfiwafi** [comment]
Hi,
My question would be surely absurd but did you try to write sudo before compiling the build script?
