### ISSUE TITLE
Not running on AMD 5400 and 4500

### ISSUE THREAD

**Issue by Zingam** [kmkolasinski/AwesomeBump#115]
The program hangs on startup. I was curious to try it.

[log.txt](https://github.com/kmkolasinski/AwesomeBump/files/806250/log.txt)

**Comment by kmkolasinski** [comment]
Did you try different versions? AB has problems with AMD graphics cards... :/ The error in the log file is completely not informative.

**Comment by Zingam** [comment]
I'll try try other versions than 5 now.

Here is the log from them HD 4500. GL3 version.

I could try to debug it myself but I won't be able to do it in a reasonable amount of time anyway.
[log.txt](https://github.com/kmkolasinski/AwesomeBump/files/810752/log.txt)

**Comment by kmkolasinski** [comment]
Hi,
there is a problem with shader compilation:
```
ERROR: 2:1074: error(#30) Built-in function parameter type check fail: offset must be a constant/literal in texture functions Offset should be a constant expression
```
It seems that you have an old graphics card or old graphics drivers. 
See last comment ![here](http://stackoverflow.com/questions/25440114/argument-4-to-function-texelfetchoffset-must-be-a-constant-expression)
The problem is in that line: 
```GLSL
highp float Rx  = textureOffset(layerA, tex_coord, dx).x;
```
Solving it we could make AB working. I hope... Which system do you use? and can you compile AB by  yourself.

**Comment by Zingam** [comment]
Hi,

I'll help debugging this. My knowledge about OpenGL is rudimentary and mostly theoretical but I need to get upto the speed rather quickly anyway. I'll compile the project and I'll report back.

I use two old HP laptops one has Radeon HD4500 (OpenGL 3.3) and the other one Radeon HD5400 (OpenGL 4.3) I believe. The drivers are the latest available for both but still old.

BTW. I don't see the last comment - there is just a broken image: Non-Image content-type returned

**Comment by kmkolasinski** [comment]
Hi, the link was broken. I have updated windows binaries yesterday which contains fix for your problem. If you are using Win7 you can try to run AwesomeBump5.1 version.

**Comment by Zingam** [comment]
The program still hangs after loading the GUI. This are the logs of my HD5000 series laptop.

[log.txt](https://github.com/kmkolasinski/AwesomeBump/files/818669/log.txt)
[log33.txt](https://github.com/kmkolasinski/AwesomeBump/files/818670/log33.txt)

**Comment by kmkolasinski** [comment]
Did you tried newer graphics drivers? Version  gl330 is working on my old laptop with HD4720 and win7.

**Comment by Zingam** [comment]
I forgot to mention that I am on Windows 10. According to AMD:
_Driver support for these products under Windows® 8.1 and Windows® 10 is only available via Windows Update. Please enable Windows Update to allow it to automatically detect and install display driver version 8.970.100.9001_

I am on the latest drivers for Win10.

Just for the record here is the log of gl330 on HD4500.

I'm downloading Qt now to compile it myself.

[log.txt](https://github.com/kmkolasinski/AwesomeBump/files/819118/log.txt)

**Comment by kmkolasinski** [comment]
Peculiar the last log does not show any errors, why is that ?
