### ISSUE TITLE
OpenGL 3?

### ISSUE THREAD

**Issue by rredesigns** [kmkolasinski/AwesomeBump#117]
Hello.

I was wondering if it is possible to make this application run with OpenGL3 instead of 4, since what we all care about are the filters that create the maps and the maps themselves, not the PBR visualization.

**Comment by ppiecuch** [comment]
Hi - check BuildingInstruction.pdf for information how to configure AB for building with OpenGL 3 - but I think you have to build the app. from the sources (no binary release for OpenGL3).

Regards
Pawel

**Comment by rredesigns** [comment]
That's good news, I'll check it out.

I can use OpenGL 4.5 with Windows, but all my other stuff are used under Linux, I don't want to boot other OS if I can make this work with v3. For some reason the open source drivers are not quite there yet. 

Thank you.

**Comment by rredesigns** [comment]
It doesn't seem to build at all without a higher version of OpenGL. I can only get a warning and that's it. :(

**Comment by rredesigns** [comment]
No, it doesn't. Not under Linux, because the open source drivers (which are Intel's official drivers for Linux), are barely at v3.0. Here's my console output: 

```
$ glxinfo | grep OpenGL
OpenGL vendor string: Intel Open Source Technology Center
OpenGL renderer string: Mesa DRI Intel(R) Haswell Desktop 
OpenGL core profile version string: 4.5 (Core Profile) Mesa 17.0.1
OpenGL core profile shading language version string: 4.50
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile
OpenGL core profile extensions:
OpenGL version string: 3.0 Mesa 17.0.1
OpenGL shading language version string: 1.30
OpenGL context flags: (none)
OpenGL extensions:
OpenGL ES profile version string: OpenGL ES 3.1 Mesa 17.0.1
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.10
OpenGL ES profile extensions:
```

As you can see, even though I have the latest drivers (Mesa 17 is the last), I still can get past OpenGL 3.0. 

And I'm only asking this because if I can see good previews in Blender material mode in the 3D viewport I assume this program would work with OpenGL 3 too, without losing too many visualization features.

**Comment by kmkolasinski** [comment]
I expect what will be your answer, but I have to ask: why don't you try proprietary drivers?

**Comment by rredesigns** [comment]
Mmm...I assume you are not a Linux user. xD

There are not such drivers for Intel's itegrated graphics. These drivers are open source and developed by the community and Intel together. This are the official Intel graphics.

I know that Nvidia and Ati cards are handling OpenGL 4.3 at this very moment, but I don't have a dedicated graphics card unfortunately.

**Comment by kmkolasinski** [comment]
Ok, now I understand, I didn't notice in your message that you have Intel's graphics card on board. You could try to build earlier versions of AB, they were much simpler to build and probably easier to convert to GL3.0. See the release tab on github project for earlier versions.

**Comment by rredesigns** [comment]
I will tray that. How should I do it? Do I need to pass a specific parameter to the compiler or just hit the build button?

**Comment by kmkolasinski** [comment]
I downloaded source code version 1.0 [ABv1.0](https://github.com/kmkolasinski/AwesomeBump/releases/tag/Linuxv1.0) and opened the project in the QtCreator. Then pressed build (you should see few warnings) and run. Just checked it few minutes ago and it was working for me. However I have nvidia graphics card.

**Comment by rredesigns** [comment]
It builds for me too, but it doesn't run. Here's the app log after a run attempt:

```
[20/03/2017 17:01:03] {Debug} 		 Starting application:
[20/03/2017 17:01:03] {Debug} 		 Widget OpenGL:  3 . 0
[20/03/2017 17:01:03] {Debug} 		 Context valid:  true
[20/03/2017 17:01:03] {Debug} 		 OpenGL information: 
[20/03/2017 17:01:03] {Debug} 		 VENDOR:  Intel Open Source Technology Center
[20/03/2017 17:01:03] {Debug} 		 RENDERER:  Mesa DRI Intel(R) Haswell Desktop 
[20/03/2017 17:01:03] {Debug} 		 VERSION:  3.0 Mesa 17.0.1
[20/03/2017 17:01:03] {Debug} 		 GLSL VERSION:  1.30
[20/03/2017 17:01:03] {Debug} 		 OpenGLVersionFlags():  QFlags()
[20/03/2017 17:01:03] {Debug} 		 GL 3.2 Not supported
```

**Comment by kmkolasinski** [comment]
So the problem is still the same, and its related to intel graphics. The detected GLSL version is super old. I don't understand how it is possible that there still computer which support such things....

**Comment by rredesigns** [comment]
I'm just as surprised as you are. As you can see, I have the latest mesa drivers, but OpenGL is well behind. I'm not quite sure why that is. According to Intel's page, we should have higher OpenGL versions with Intel HD gaphics drivers. :|

I never noticed this untill now though. Blender works just fine, and it's glsl shading in the 3D viewport looks amazing (that's why I think this software could work with v.3)

**Comment by Calinou** [comment]
OpenGL versions above 3.0 are available on Mesa **only** if using Core Profile. Compatibility Profile is intentionally not supported by Mesa developers.

**Comment by rredesigns** [comment]
@Calinou I'm not sure I understand what you mean. I know almost nothing about this topic. Where can I read about that?

**Comment by rredesigns** [comment]
Ok, so how can i force the build to use the core profile? I hear that mesa won't support compatibility because no application uses it, but apparently that's not the case here.

@kmkolasinski what should i change for it to build with core profile? Sorry to ask that, but i really know nothing about opengl coding. :|

**Comment by rredesigns** [comment]
I found something interesting in the main window source. The Q_OS_MAC if that forces the core profile. I changed that to LINUX and I managed to compile v1 and v3. Unfortunately the latest won't compile, and for V3 I had to also get rid of the opengl check.

There's no visualization and it only outputs empty images for some reason. I don't know how this app was designed, but at least I'm a step closer. xD

**Comment by jagoly** [comment]
Hit the same issue. Both pre-built binaries run, but give a whole opengl bunch of errors in the log, and nothing is displayed in the 3D viewport. Using Ubuntu 16.04 w/ mesa 17.0.2.

By the look of it, a significant rewrite of AB's code would be required to get this to work with Mesa. All of the depreciated stuff would have to be removed.

**Comment by rredesigns** [comment]
That's great. With a dedicated graphics card you should be fine under Linux, both Ati and Nvidia drivers are working with OpenGL 4.5 by now. The only issue is the driver for Intel. :/

**Comment by jagoly** [comment]
Also the other mesa drivers, nouveau, radeon, etc. They are all at GL 4.5 now, but only Core Profile. There is no intention to support Compatibility Profile for 3.3/4.0+ in mesa, so they will never support AB in it's current state.

Hope things are clear now. I intend to have a look at AB's code to see if it would be feasible for me to make a fork using modern OpenGL. Also I'd have to get some info from the current maintainers to make sure that this isn't already being worked on.

**Comment by rredesigns** [comment]
I wish I could help, but my knowledge on the API is pretty much null. Hopefully you will do it sometime and people will use this more and more comfortably under Linux. Best of luck.

**Comment by BrainBlasted** [comment]
@jagoly Have you decided on whether or not you are going to be working on this?

**Comment by jagoly** [comment]
No not yet, sorry. I don't need AB at the moment but I'm sure I will in the
future, but don't count on me fixing it in a timely manner

**Comment by rredesigns** [comment]
Ok, I found a solution for now. Not as good, but does the job. If you want to use it you need to set up a local server and use Chrome (visualization doesn't work with Firefox), but it's a 3 minute install with XAMMP in Linux or Vertrigo Server in Windoze.

Here's the repo, just download and throw it into your server public folder. You can use it without server to generate the normal map only. https://github.com/cpetry/NormalMap-Online
