### ISSUE TITLE
UI enhancement request

### ISSUE THREAD

**Issue by didli** [kmkolasinski/AwesomeBump#118]
First of all, **thank you** for AwesomeBump. It's a really good app that fills a gap in the linux software workflow.
As it is, I think AwesomeBump 5.0 UI is getting a little confusing : in previous versions for example, tabs were fully named, but now it uses symbols.  
I can understand the need to avoid cluster so maybe there could be options/settings to manage the UI in the future versions ? Is it planned ?
Still, thank you again for AwesomeBump and keep up the good work !

**Comment by ppiecuch** [comment]
Hi - in my branch I am working on some improvements to UI: indeed tabs are not very functional with that many of pages - I have replaced them with combobox (looks better and can display shortcuts you can easily remember) + I am experimenting with some optional "dial pad" below combobox.

Regards
Pawel

![screen shot 2017-03-16 at 6 03 46 pm](https://cloud.githubusercontent.com/assets/1011685/24008807/1395aa3c-0a73-11e7-90f6-8fb8b21a8d62.jpg)

**Comment by didli** [comment]
Looks interesting but seems like a lot of work. As for me I would still use and be ok with tabs if they were not represented only by symbols (maybe full-grown icons ?). I've seen an old tutorial with 3.14 version, and tabs were fully named. What was the reason behind the change ? I'm thinking "not enough place anymore" ?

**Comment by ppiecuch** [comment]
Correct - tab names were heavily truncated, as some users reported (including me).
Regards
Pawel

**Comment by didli** [comment]
OK, thanks Pawel for your input, and I'm looking forward your promising work on the UI. 
Good luck ^^!
Regards,
- didli
