### ISSUE TITLE
Quadro K500

### ISSUE THREAD

**Issue by Oldguy4440** [kmkolasinski/AwesomeBump#119]
Quadro K5000 supports OpenGl 4.3 yet the program fails on launch! Program says K5000 only supports 2.1.2. Bug?

**Comment by Calinou** [comment]
What operating system, graphics driver version, and AwesomeBump version are you using? Does the OpenGL 3.3 fallback work?

**Comment by Oldguy4440** [comment]
Resolved had to manually update video drivers. Now how do I make the text bigger so these 60 year old eyes can read it?
