### ISSUE TITLE
Windows 10 Convert crash

### ISSUE THREAD

**Issue by kvanconant** [kmkolasinski/AwesomeBump#120]
I used to be able to use it on my windows 10 laptop no problem until the last week. It started when I tried to use the new 5.1 version.

After I tried that one I can not use any version without it crashing as soon as I click convert.

I'm running an i7 cpu with 16gb ram Windows 10 Pro

**Comment by jackjameshoward** [comment]
I'm also unable to use a Windows 10. 
It does state on the release that it's for Win7 so I assuming the developer knows it doesn't work for Win10.

**Comment by kmkolasinski** [comment]
Did you try to compile it from source code ?

**Comment by kvanconant** [comment]
I found out im able to convert under 2048.
If I have my image at 2048 or above it crashes immediately.

**Comment by kmkolasinski** [comment]
Maybe you have not enough RAM on your GPU? Your problem may be also related to this case:
https://support.allegorithmic.com/documentation/display/SPDOC/GPU+drivers+crash+with+long+computations

**Comment by Koreanman01** [comment]
When I uninstalled 5.1 and installed the version before, I can do 2048. I've narrowed it down to only 5.1 and 2048 and larger.
But of my pc's even my desktop with 1gb in my gpu crashes on 2048 convert.
