### ISSUE TITLE
'activelavel' missing from master

### ISSUE THREAD

**Issue by bartoszek** [kmkolasinski/AwesomeBump#122]
There is no Source/utils/activelabel.(h/cpp) in master.
Perhaps incomplete commit...

**Comment by ppiecuch** [comment]
You should find it in my branch: origin/ppiecuch_osx_wip
Regards
P.

**Comment by kmkolasinski** [comment]
What it this actually ? I don't know those files and why they are not in master ?

**Comment by kmkolasinski** [comment]
Wow, I made AB compilable with last commit but GUI  does not work... @ppiecuch why gui is in that shape :D nothing is working properly, damn! I haven't looked at the code since many months.

**Comment by kmkolasinski** [comment]
I made a stable and working Release branch - this one is now the default one. All experiments and not tested modifications should be done on any other branch.

**Comment by ppiecuch** [comment]
Hello,
activelabel is good for creating small buttons, like this:


Must be I committed some other change and reference to activelabel have been included.

Regards
Pawel

**Comment by kmkolasinski** [comment]
@ppiecuch  I don't see anything in your post (blank lines) :( 
Master branch is now not working properly on linux.

**Comment by ppiecuch** [comment]
Buttons like these:
![screen shot 2017-07-10 at 6 50 37 pm](https://user-images.githubusercontent.com/1011685/28131840-733a9fea-673b-11e7-9ee7-29a6054f7df7.jpeg)

P.
