### ISSUE TITLE
Fragment shader fault to compile..offset must be a constant in texture functions

### ISSUE THREAD

**Issue by GentleHedgehog** [kmkolasinski/AwesomeBump#125]
I have Qt5.7 and Mingw32. Debug messages say: "Fragment shader fault to compile ... offset must be a constant in texture functions". What is going wrong?

**Comment by kmkolasinski** [comment]
Which graphics card do you have ?

**Comment by GentleHedgehog** [comment]
AMD Radeon r7 200 series

**Comment by kmkolasinski** [comment]
Are you compiling AB from sources ?

**Comment by GentleHedgehog** [comment]
Yes, it compiles normally but it doesnt display images properly - only black squares instead

**Comment by kmkolasinski** [comment]
Ok, great since you are compiling this, you can fix this bug. For some reason AMD cards are less tolerant in case of GLSL shaders and does not compile. Could you paste here the fragment of the log with the error. I will instruct you  where to change the code and fix that problem.

**Comment by GentleHedgehog** [comment]
I run the app and then stop it: https://cloud.mail.ru/public/VsH8/PQuyoNpkS

**Comment by kmkolasinski** [comment]
This page is empty for me i.e. there is no content just blank page.

**Comment by GentleHedgehog** [comment]
May be you need to wait a little, in order to get a button for download 
![screenshot_2017-07-20-11-05-21](https://user-images.githubusercontent.com/3767353/28407112-9d258972-6d3b-11e7-93cf-89eaadd0c1aa.png)

**Comment by GentleHedgehog** [comment]
I sent to awesomebump.help@gmail.com

**Comment by kmkolasinski** [comment]
It seems that the problem is with this lines:
```
    const vec2 size = vec2(1.0,0.0);
    const ivec3 off = ivec3(-1,0,1);
    const ivec2 dx  = ivec2(1,0);
    const ivec2 dy  = ivec2(0,1);
    vec2 tex_coord =  v2QuadCoords.st;
    highp float R0  = texture(layerA, tex_coord).x;

    // (dx,dy)
    highp float Rx  = textureOffset(layerA, tex_coord, dx).x;
    highp float Ry  = textureOffset(layerA, tex_coord, dy).x;
    highp vec3 dRx  = normalize(vec3(size.xy,gui_hn_conversion_depth*(Rx-R0)));
    highp vec3 dRy  = normalize(vec3(size.yx,gui_hn_conversion_depth*(Ry-R0)));
    highp vec3 bump = normalize( cross(dRx,dRy) );

    // (-dx,-dy)
    Rx  = textureOffset(layerA, tex_coord, -dx).x;
    Ry  = textureOffset(layerA, tex_coord, -dy).x;
   
```
https://github.com/kmkolasinski/AwesomeBump/blob/Release/Sources/resources/shaders/filters.frag#L1072


Your shader compilator for some reason requires `textureOffset(layerA, tex_coord, dx).x;` to have constant literals. 
`
offset must be a constant/literal in texture functions
`
Try to replace `dx` and `dy` with explicit values, like:
```
highp float Rx  = textureOffset(layerA, tex_coord, ivec2(1,0)).x;
```
Is the error the same?

**Comment by GentleHedgehog** [comment]
Thank you for advice, but I got an error after change dx to ivec2(1,0) , dy to ivec2(0,1) - the program crashes with pointing at atioglxx.dll ..

Debug output:
...
Loading filters (vertex shader)
done // after this message - crash

**Comment by kmkolasinski** [comment]
and what about log file?

**Comment by GentleHedgehog** [comment]
I sent to awesomebump.help@gmail.com

**Comment by kmkolasinski** [comment]
Ok, I have no idea where is the problem. Did you try to build AB with opengl 330 mode?

**Comment by GentleHedgehog** [comment]
Yes, I got the same result

**Comment by kmkolasinski** [comment]
Do you have recent GPU drivers? or at least you can try to build one of older versions of AB.

**Comment by GentleHedgehog** [comment]
I will try to update driver tomorrow

**Comment by GentleHedgehog** [comment]
I'v coped with the problem after update drivers :-). And I have another question, can I do conversions of images without gui? Now I get black images after conversion in a console mode.

**Comment by kmkolasinski** [comment]
There is not console mode for AB, however there is a batch tool which you can use to process multiple images. Is this what you need?

**Comment by GentleHedgehog** [comment]
I want to use the batch tool in console mode, I change some code to do it, but the app generates only black images in this case

**Comment by kmkolasinski** [comment]
Hmmm, hard to say, since I was writing this code with GUI app in my mind. However as far as I remember widgets are needed to initialize some Frame buffers for rendering off-screen. Maybe when you want to draw to FBO and gui was not initialized there is nothing to draw into it. Just guessing. At your place I would start with some custom FBO and try to render image into it. If this will work, then you could try to app rendering pipeline step by step. Is this clear ?

**Comment by GentleHedgehog** [comment]
Thank you for advice, now I look at QOpenGLContext and QOffscreenSurface, after read this -https://stackoverflow.com/questions/17221730/do-offscreen-renderopengl-with-qt5

**Comment by kmkolasinski** [comment]
Good luck then. If you will manage to solve your problem are you going to make some pull-request with this features. Many people were asking about it.
