### ISSUE TITLE
Batch process directory?

### ISSUE THREAD

**Issue by polarathene** [kmkolasinski/AwesomeBump#126]
If I input an image and make some tweaks then setup the export for image maps I'm interested in, would it be possible to have all the tweaks/settings saved and then support batch processing a directory of input images to a directory of output images?

**Comment by kmkolasinski** [comment]
Did you try to use project manager?

**Comment by polarathene** [comment]
@kmkolasinski When I wrote the issue earlier in the day it turns out I was using an older version(5.0) from Arch Linux's AUR, they've not updated to 5.1 which I tried later in the day after reporting this issue on Windows to show off the excellent software :) Discovered the batch process directory feature there. Sorry about that!

**Comment by kmkolasinski** [comment]
Ok, thanks for feedback!
