### ISSUE TITLE
Height to normal, 16-bit depth support?

### ISSUE THREAD

**Issue by polarathene** [kmkolasinski/AwesomeBump#127]
Similar to [this issue](https://github.com/kmkolasinski/AwesomeBump/issues/79), I tried to create a normal map from height with AB and saw banding. Presumably the 16-bit was processed/read as 8-bit(or produced an 8-bit normal?). In comparison a similar tool Knald does not have this quality issue when converting height to normal.

**Comment by kmkolasinski** [comment]
I didn't solve this problem correctly, but I've added a noise button which add small noise to generated normal, and the effect is less visible. Did you try it?
