### ISSUE TITLE
UI too small on HiDPi Display

### ISSUE THREAD

**Issue by hubslave** [kmkolasinski/AwesomeBump#131]
Hello, I tried to run AwesomeBump on HiDPi Display but UI is too small. Please do you have some advice how can I fix it? Thank you very much and have a nice day :)

![screenshot from 2017-09-12 16-54-00](https://user-images.githubusercontent.com/29800872/30332678-3afcdfc8-97db-11e7-8904-6d14ddc719d7.png)

**Comment by kmkolasinski** [comment]
Hi try to change the font size in config file: 
https://github.com/kmkolasinski/AwesomeBump/blob/Release/Bin/Configs/gui.ini
It should help.

**Comment by hubslave** [comment]
Thank you very much, please could you tell me where can I find this config file when I use appimage version of AwesomeBump?

**Comment by kmkolasinski** [comment]
It should be located in Configs/gui.ini folder. The same place where are the binaries

**Comment by hubslave** [comment]
Thank you. :) It is better now but there are still some problems... For example some icons are small, which is a little bit inconvenient but it is not a big problem.

![awesomebumpbug](https://user-images.githubusercontent.com/29800872/30435807-faac9026-996a-11e7-918d-3eb71fca36aa.png)

But in some menus some margins cover parts of the UI. I did not find a way how to move/resize these margins. :/

**Comment by kmkolasinski** [comment]
Sorry but icons have fixed size.

**Comment by hubslave** [comment]
Also the margin which I painted red on the example image is fixed? It seems it can't be moved

**Comment by kmkolasinski** [comment]
The margin is movable. Oh maybe you approached it maximum size. Other tabs have the same problem?

**Comment by hubslave** [comment]
Oh I now realized that I was picking the margin in the wrong space, I should pick in on the border with viewport. Now I see - yes I am able to make it smaller but not bigger so you are probably right, I probably reached maximum size. Yes other tabs have the same behavior - I get "maximum size out of the box" and cant make it any bigger leaving some tabs partially hidden.

**Comment by Mnc2g** [comment]
Hello,
thank you so much for this piece of software, the best in my opinion.
I get this behavior, do you have any suggestions? Many thanks!
![awesomebump issue 4k](https://user-images.githubusercontent.com/45915140/51784623-18deda80-214c-11e9-9250-e80efd186a1a.png)

**Comment by kmkolasinski** [comment]
wow! first time seeing such thing. To my opinion it looks like exactly half of the viewport. What kind of system do you have ? Are you able to build AB from source ?

**Comment by Mnc2g** [comment]
Hi, it's Ubuntu 18.10, Kubuntu flavor. 
re: Are you able to build AB from source?
Never did that, but I can try, could you suggest where I could find the information to build it?
Thank you!

**Comment by kmkolasinski** [comment]
On ubuntu it is quite easy, you must have Qt 5 libraries installed (this can be done with apt-get install).
Then, the steps you need to perform are:
* open terminal somewhere
* clone repository: `git clone https://github.com/kmkolasinski/AwesomeBump.git`
* `cd AwesomeBump`
* set the correct path to the Qt library in the `unixBuildScript.sh` script. It should be something like that: `MY_QT_PATH=/opt/Qt5.7.0/5.7/gcc_64/bin/`
* run script: `./unixBuildScript.sh` it should take around 5 minutes to build. In Bin folder you will find compiled Awesomebump binary. Try to run it and report me if everything works fine.

**Comment by Mnc2g** [comment]
Thank you very much for the detailed information.
There were a couple of issues, but at the third effort I could build it.
Unfortunately nothing changed, I still have that black area surrounding the 3D view and the map.
Something else to try?
Thanks again

**Comment by kmkolasinski** [comment]
Firstly: everything but that works fine? 
Secondly, we have to check what is the viewport size and what is the Qt widget size, the easiest way to do it is to add `qDebug()` in multiple places in the code. Those information will be then added to log.txt. 
So for example you can try to add debug line here:

https://github.com/kmkolasinski/AwesomeBump/blob/Release/Sources/glwidget.cpp#L506
```
qDebug() << "##SOME FANCY DEBUG HERE## width=" << width() << " height=" << height() ;
```
where width() and height() are functions which should return widget dimension i.e. the rendring window size, those numbers should be in pixels so you should be able to compare them with real size of the window in the running application. The second place is a function which is called every time you change the size of the application:

https://github.com/kmkolasinski/AwesomeBump/blob/Release/Sources/glwidget.cpp#L784

You can add there similar debug information. Then compile the code and run AB. Look for your debug messages in the log.txt. 
Are those numbers bigger than rendered image ? I wonder if this is something related to Qt or OpenGl.

**Comment by Mnc2g** [comment]
Hello

1. Everything works
2. I put the code `qDebug() << "##SOME FANCY DEBUG HERE## width=" << width() << " height=" << height() ;` at row number 507 and 783. Compiled and used AB, however I couldn't find any log.txt file. I expected to find it in the AB directory

Thanks again

**Comment by kmkolasinski** [comment]
This is rather not possible, please make sure that you have saved the file and you are looking at the valid log.txt. It should be in the Bin folder.

**Comment by Mnc2g** [comment]
Actually noticed that I get the information on standard output, running the application from command line.
First run:
`# width= 453  height= 534 (window 800 x 600)`
Then full screen:
`# width= 672  height= 959 (window 1915 x 1046)`
Please let me know your comments, thank you.

**Comment by kmkolasinski** [comment]
Ok, so clearly there is something wrong, since these numbers should be equal. Maybe they change something in the Qt API and width() function returns some relative value, just guessing. Which version of Qt do you have? `5.7.0` ?

Can you confirm that mouse dragging and zooming works fine in your case? I mean try to drag texture image in the right window, it should follow mouse movement. It is consistent with mouse displacement? 

Let's do some hack, please change one line: https://github.com/kmkolasinski/AwesomeBump/blob/Release/Sources/glimageeditor.cpp#L364
to:
```
GLCHK( glViewport(0,0,width()*2,height()*2) );
```
This should make viewport twice bigger, however mouse bahaviour now should be broken.

**Comment by kmkolasinski** [comment]
Could you make similar debug for this place: https://github.com/kmkolasinski/AwesomeBump/blob/Release/Sources/glimageeditor.cpp#L1018

What are the values for width and height variables, and is this the same what width() height() functions.
```
qDebug() << height << "\t" << this->height();
```

**Comment by Mnc2g** [comment]
Hi,

1. 5.11.1+dfsg-7ubuntu1 (correct?)
2. Mouse dragging and zooming works fine
3. The good news is that with maximized screen the map is bigger and mouse works

any adivce?

![immagine](https://user-images.githubusercontent.com/45915140/52016423-ceab7f80-24e4-11e9-8690-e956acc445ab.png)

**Comment by kmkolasinski** [comment]
Ok, I have 5.7, so I guess that maybe this is related to the difference in versions ... 
If you are fine with this resized window we can make the second one bigger ?

**Comment by Mnc2g** [comment]
yes sure, what file is that? Thanks

**Comment by kmkolasinski** [comment]
The second one is more tricky, I will try to find out (this evening) in which places you will need to scale rendered window.

**Comment by kmkolasinski** [comment]
Ok, this line does the thing: https://github.com/kmkolasinski/AwesomeBump/blob/Release/Sources/glwidget.cpp#L506

**Comment by Mnc2g** [comment]
Hi, thank you very much.
Unfortunately only the content of the window has been zoomed, the windows itself remains of the same size.
Thanks
![immagine](https://user-images.githubusercontent.com/45915140/52164761-cb87dd80-26f6-11e9-82be-88530d1b95e1.png)

**Comment by kmkolasinski** [comment]
Ok, this may happen since there are many places with 
```
GLCHK( glViewport(0,0,width(),height()) );
```
You can try first comment all post processing. Comment these lines in paintGL function:
```
    // do post processing if materials are not shown
    if( keyPressed != KEY_SHOW_MATERIALS ){

        copyTexToFBO(colorFBO->fbo->texture(),outputFBO->fbo);

        // -----------------------------------------------------------
        // Post processing:
        // 1. Bloom (can be disabled/enabled by gui)
        // -----------------------------------------------------------
        // enable of disable bloom effect
        if(display3Dparameters.bBloomEffect){
             applyGlowFilter(outputFBO->fbo);
        }// end of if bloom effect

        // -----------------------------------------------------------
        // Post processing:
        // 2. DOF (can be disabled/enabled by gui)
        // -----------------------------------------------------------
        if(display3Dparameters.bDofEffect){
            applyDofFilter(colorFBO->fbo->texture(),outputFBO->fbo);            
        }

        // -----------------------------------------------------------
        // Post processing:
        // 3. Lens Flares (can be disabled/enabled by gui)
        // -----------------------------------------------------------
        if(display3Dparameters.bLensFlares){
            applyLensFlaresFilter(colorFBO->fbo->texture(),outputFBO->fbo);
        }

        applyToneFilter(colorFBO->fbo->texture(),outputFBO->fbo);


        applyNormalFilter(outputFBO->fbo->texture());

    }else{ // end of if SHOW MATERIALS TEXTURE DISABLED
        GLCHK( applyNormalFilter(colorFBO->fbo->texture()));
    }
```
Then add following line (just below commented code):
```
GLCHK( applyNormalFilter(colorFBO->fbo->texture()));
```
This will render only the 3D scene without DOF, bloom etc, I want to eliminate all potential problems. 
Now you can try to modify `GLCHK( glViewport(0,0,width(),height()) );` call in 
the `applyNormalFilter` function in the same file:

```
void GLWidget::applyNormalFilter(GLuint input_tex){

    filter_program = post_processing_programs["NORMAL_FILTER"];
    filter_program->bind();
    GLCHK( glViewport(0,0,width() * 2, height() * 2) );
    GLCHK( filter_program->setUniformValue("quad_scale", QVector2D(1.0,1.0)) );
    GLCHK( filter_program->setUniformValue("quad_pos"  , QVector2D(0.0,0.0)) );
    GLCHK( glActiveTexture(GL_TEXTURE0) );
    GLCHK( glBindTexture(GL_TEXTURE_2D, input_tex) );

    GLCHK( quad_mesh->drawMesh(true) );
}
```
Hope this will work for you, otherwise I have no idea what else may be wrong.

**Comment by Mnc2g** [comment]
Hi, thank you very much!
I had to revert at row [https://github.com/kmkolasinski/AwesomeBump/blob/Release/Sources/glwidget.cpp#L506](https://github.com/kmkolasinski/AwesomeBump/blob/Release/Sources/glwidget.cpp#L506)
and change row 1208
[https://github.com/kmkolasinski/AwesomeBump/blob/Release/Sources/glwidget.cpp#L1206](https://github.com/kmkolasinski/AwesomeBump/blob/Release/Sources/glwidget.cpp#L1206)
I have to test it thoroughly, but for now it works perfectly!
Thank you very much!

**Comment by kmkolasinski** [comment]
Cool, glad it works and have fun :)
