### ISSUE TITLE
strange issue

### ISSUE THREAD

**Issue by brothermechanic** [kmkolasinski/AwesomeBump#132]
https://i.imgur.com/NjHBa11.jpg
no reaction on sliders changes

**Comment by kmkolasinski** [comment]
Did you try other tabs? other sliders? What about logs?

**Comment by brothermechanic** [comment]
Hello!
Glad to see you!
Other tabs too

**Comment by kmkolasinski** [comment]
Hello :)
Maybe it is worth to check log file. I stop my works with AB. Your problem is kind of strange. First time seeing such issue here.

**Comment by brothermechanic** [comment]
Something shanges only if i push 
Recalculate from Height button
https://i.imgur.com/OC33eWj.jpg
it works as Apply

**Comment by kmkolasinski** [comment]
It's aliasing problem. You should smoothen your normal or height. Try with different images.

**Comment by brothermechanic** [comment]
No
I thin it qt/kde problem or so
When i make some changes of values - nothing happened
BUT, when i switch to another window - all start to work, and i see changes
My system is 
kde-5.10.5
qt-5.9.1
gcc-7.2
glibc- 2.26

**Comment by kmkolasinski** [comment]
I cannot help you then. I work with gnome normally.

**Comment by kmkolasinski** [comment]
I believe this has been resolved in the new release
