### ISSUE TITLE
Legacy Qt GL

### ISSUE THREAD

**Issue by ppiecuch** [kmkolasinski/AwesomeBump#133]
I was finally managed to remove legacy Qt OpenGL code (in my branch). I using QOpenGLTexture/Framebuffer for everything and QOpenGLWidget. Major challenge was to share context between all elements: QOpenGLWidget shares context by default; each FormImageProp has now its own offline surface (qtofflinegl.h) that shares context with global one. 

One of the benefit is that I could remove update hack from GLWidgetBase - QOpenGLWidget seems to manage repeating update events.

Still I am not able to display in glwidget (Intel GPU) but at least, Qt code seems to be a bit cleaner :)

P.

**Comment by kmkolasinski** [comment]
Hi, thanks for feedback. Could you write exactly which branch do you mean ?

**Comment by ppiecuch** [comment]
ppiecuch_osx_wip
One of the last bigger think I would like to test and experiment is an option for background rendering - this is something I think of from the beginning, e.g.:

    updateImage(DIFFUSE_TEXTURE);
    updateImage(ROUGHNESS_TEXTURE);
    updateImage(METALLIC_TEXTURE);
    updateImage(HEIGHT_TEXTURE);
    // recalulate normal at the end
    updateImage(NORMAL_TEXTURE);
    // then ambient occlusion
    updateImage(OCCLUSION_TEXTURE);
    updateImage(SPECULAR_TEXTURE);
    updateImage(MATERIAL_TEXTURE);

this sequence should trigger and queue 8 requests to background renderer for 8 textures - background renderer should signal each texture with some textureReady() signal. I started to work on this in threadrenderer.cpp class - that way I would like to remove all processing from gui/main thread.

P.

**Comment by kmkolasinski** [comment]
This will probably never done :)
