### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by pmiddend** [kmkolasinski/AwesomeBump#134]
When I try to run AwesomeBump (I'm on nixos btw.), I get a segmentation fault. Digging further with gdb, the following is output:

Thread 1 "AwesomeBump" received signal SIGSEGV, Segmentation fault.
0x000000000041b419 in GLWidget::paintGL() ()
(gdb) bt
#0  0x000000000041b419 in GLWidget::paintGL() ()
#1  0x00007ffff7ba1a34 in QGLWidget::glDraw() () from /nix/store/yxyg5dykv5s7hzvfdg1745zz2rzkdypm-qtbase-5.9.2/lib/libQt5OpenGL.so.5
#2  0x00007ffff7ba13dd in QGLWidget::paintEvent(QPaintEvent*) () from /nix/store/yxyg5dykv5s7hzvfdg1745zz2rzkdypm-qtbase-5.9.2/lib/libQt5OpenGL.so.5
#3  0x00007ffff74c0e40 in QWidget::event(QEvent*) () from /nix/store/yxyg5dykv5s7hzvfdg1745zz2rzkdypm-qtbase-5.9.2/lib/libQt5Widgets.so.5
#4  0x00007ffff7481f5c in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /nix/store/yxyg5dykv5s7hzvfdg1745zz2rzkdypm-qtbase-5.9.2/lib/libQt5Widgets.so.5
#5  0x00007ffff748977b in QApplication::notify(QObject*, QEvent*) () from /nix/store/yxyg5dykv5s7hzvfdg1745zz2rzkdypm-qtbase-5.9.2/lib/libQt5Widgets.so.5
#6  0x00007ffff6834e7a in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /nix/store/yxyg5dykv5s7hzvfdg1745zz2rzkdypm-qtbase-5.9.2/lib/libQt5Core.so.5
#7  0x00007ffff74b9dea in QWidgetPrivate::sendPaintEvent(QRegion const&) () from /nix/store/yxyg5dykv5s7hzvfdg1745zz2rzkdypm-qtbase-5.9.2/lib/libQt5Widgets.so.5
#8  0x00007ffff74ba44f in QWidgetPrivate::drawWidget(QPaintDevice*, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) ()
   from /nix/store/yxyg5dykv5s7hzvfdg1745zz2rzkdypm-qtbase-5.9.2/lib/libQt5Widgets.so.5
#9  0x00007ffff748f872 in QWidgetPrivate::repaint_sys(QRegion const&) () from /nix/store/yxyg5dykv5s7hzvfdg1745zz2rzkdypm-qtbase-5.9.2/lib/libQt5Widgets.so.5
#10 0x00007ffff74dc97c in ?? () from /nix/store/yxyg5dykv5s7hzvfdg1745zz2rzkdypm-qtbase-5.9.2/lib/libQt5Widgets.so.5
#11 0x00007ffff74dd3a3 in ?? () from /nix/store/yxyg5dykv5s7hzvfdg1745zz2rzkdypm-qtbase-5.9.2/lib/libQt5Widgets.so.5
#12 0x00007ffff7481f5c in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /nix/store/yxyg5dykv5s7hzvfdg1745zz2rzkdypm-qtbase-5.9.2/lib/libQt5Widgets.so.5
#13 0x00007ffff748977b in QApplication::notify(QObject*, QEvent*) () from /nix/store/yxyg5dykv5s7hzvfdg1745zz2rzkdypm-qtbase-5.9.2/lib/libQt5Widgets.so.5
#14 0x00007ffff6834e7a in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /nix/store/yxyg5dykv5s7hzvfdg1745zz2rzkdypm-qtbase-5.9.2/lib/libQt5Core.so.5
#15 0x00007ffff6d7f6bd in QGuiApplicationPrivate::processExposeEvent(QWindowSystemInterfacePrivate::ExposeEvent*) ()
   from /nix/store/yxyg5dykv5s7hzvfdg1745zz2rzkdypm-qtbase-5.9.2/lib/libQt5Gui.so.5
#16 0x00007ffff6d802ed in QGuiApplicationPrivate::processWindowSystemEvent(QWindowSystemInterfacePrivate::WindowSystemEvent*) ()
   from /nix/store/yxyg5dykv5s7hzvfdg1745zz2rzkdypm-qtbase-5.9.2/lib/libQt5Gui.so.5
#17 0x00007ffff6d5cf7b in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) ()
   from /nix/store/yxyg5dykv5s7hzvfdg1745zz2rzkdypm-qtbase-5.9.2/lib/libQt5Gui.so.5
#18 0x00007ffff7fa6570 in ?? () from /nix/store/zp4gbr664jki3wipxlk1xhl1vpj5cz55-qtbase-5.9.2/lib/libQt5XcbQpa.so.5
#19 0x00007ffff2194077 in g_main_context_dispatch () from /nix/store/kliglwjyvmb5q7as39lxp01c3fnwnfqb-glib-2.54.1/lib/libglib-2.0.so.0
#20 0x00007ffff21942e8 in g_main_context_iterate.isra () from /nix/store/kliglwjyvmb5q7as39lxp01c3fnwnfqb-glib-2.54.1/lib/libglib-2.0.so.0
#21 0x00007ffff219439c in g_main_context_iteration () from /nix/store/kliglwjyvmb5q7as39lxp01c3fnwnfqb-glib-2.54.1/lib/libglib-2.0.so.0
#22 0x00007ffff6884d8f in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /nix/store/yxyg5dykv5s7hzvfdg1745zz2rzkdypm-qtbase-5.9.2/lib/libQt5Core.so.5
#23 0x000000000042677c in MainWindow::initializeImages() ()
#24 0x00000000004ba538 in MainWindow::qt_static_metacall(QObject*, QMetaObject::Call, int, void**) ()
#25 0x00007ffff685d50f in QMetaObject::activate(QObject*, int, int, void**) () from /nix/store/yxyg5dykv5s7hzvfdg1745zz2rzkdypm-qtbase-5.9.2/lib/libQt5Core.so.5
#26 0x00007ffff7ba1a34 in QGLWidget::glDraw() () from /nix/store/yxyg5dykv5s7hzvfdg1745zz2rzkdypm-qtbase-5.9.2/lib/libQt5OpenGL.so.5
#27 0x00007ffff7ba13dd in QGLWidget::paintEvent(QPaintEvent*) () from /nix/store/yxyg5dykv5s7hzvfdg1745zz2rzkdypm-qtbase-5.9.2/lib/libQt5OpenGL.so.5
#28 0x00007ffff74c0e40 in QWidget::event(QEvent*) () from /nix/store/yxyg5dykv5s7hzvfdg1745zz2rzkdypm-qtbase-5.9.2/lib/libQt5Widgets.so.5
#29 0x00007ffff7481f5c in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /nix/store/yxyg5dykv5s7hzvfdg1745zz2rzkdypm-qtbase-5.9.2/lib/libQt5Widgets.so.5
#30 0x00007ffff748977b in QApplication::notify(QObject*, QEvent*) () from /nix/store/yxyg5dykv5s7hzvfdg1745zz2rzkdypm-qtbase-5.9.2/lib/libQt5Widgets.so.5
#31 0x00007ffff6834e7a in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /nix/store/yxyg5dykv5s7hzvfdg1745zz2rzkdypm-qtbase-5.9.2/lib/libQt5Core.so.5
#32 0x00007ffff74b9dea in QWidgetPrivate::sendPaintEvent(QRegion const&) () from /nix/store/yxyg5dykv5s7hzvfdg1745zz2rzkdypm-qtbase-5.9.2/lib/libQt5Widgets.so.5
#33 0x00007ffff74ba44f in QWidgetPrivate::drawWidget(QPaintDevice*, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) ()
   from /nix/store/yxyg5dykv5s7hzvfdg1745zz2rzkdypm-qtbase-5.9.2/lib/libQt5Widgets.so.5
#34 0x00007ffff748f872 in QWidgetPrivate::repaint_sys(QRegion const&) () from /nix/store/yxyg5dykv5s7hzvfdg1745zz2rzkdypm-qtbase-5.9.2/lib/libQt5Widgets.so.5
#35 0x00007ffff74dc97c in ?? () from /nix/store/yxyg5dykv5s7hzvfdg1745zz2rzkdypm-qtbase-5.9.2/lib/libQt5Widgets.so.5
#36 0x00007ffff74dd3a3 in ?? () from /nix/store/yxyg5dykv5s7hzvfdg1745zz2rzkdypm-qtbase-5.9.2/lib/libQt5Widgets.so.5
#37 0x00007ffff7481f5c in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /nix/store/yxyg5dykv5s7hzvfdg1745zz2rzkdypm-qtbase-5.9.2/lib/libQt5Widgets.so.5
#38 0x00007ffff748977b in QApplication::notify(QObject*, QEvent*) () from /nix/store/yxyg5dykv5s7hzvfdg1745zz2rzkdypm-qtbase-5.9.2/lib/libQt5Widgets.so.5
#39 0x00007ffff6834e7a in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /nix/store/yxyg5dykv5s7hzvfdg1745zz2rzkdypm-qtbase-5.9.2/lib/libQt5Core.so.5
#40 0x00007ffff6d7f6bd in QGuiApplicationPrivate::processExposeEvent(QWindowSystemInterfacePrivate::ExposeEvent*) ()
   from /nix/store/yxyg5dykv5s7hzvfdg1745zz2rzkdypm-qtbase-5.9.2/lib/libQt5Gui.so.5
#41 0x00007ffff6d802ed in QGuiApplicationPrivate::processWindowSystemEvent(QWindowSystemInterfacePrivate::WindowSystemEvent*) ()
   from /nix/store/yxyg5dykv5s7hzvfdg1745zz2rzkdypm-qtbase-5.9.2/lib/libQt5Gui.so.5
#42 0x00007ffff6d5cf7b in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) ()
   from /nix/store/yxyg5dykv5s7hzvfdg1745zz2rzkdypm-qtbase-5.9.2/lib/libQt5Gui.so.5
#43 0x00007ffff7fa6570 in ?? () from /nix/store/zp4gbr664jki3wipxlk1xhl1vpj5cz55-qtbase-5.9.2/lib/libQt5XcbQpa.so.5
#44 0x00007ffff2194077 in g_main_context_dispatch () from /nix/store/kliglwjyvmb5q7as39lxp01c3fnwnfqb-glib-2.54.1/lib/libglib-2.0.so.0
#45 0x00007ffff21942e8 in g_main_context_iterate.isra () from /nix/store/kliglwjyvmb5q7as39lxp01c3fnwnfqb-glib-2.54.1/lib/libglib-2.0.so.0
#46 0x00007ffff219439c in g_main_context_iteration () from /nix/store/kliglwjyvmb5q7as39lxp01c3fnwnfqb-glib-2.54.1/lib/libglib-2.0.so.0
#47 0x00007ffff6884d8f in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /nix/store/yxyg5dykv5s7hzvfdg1745zz2rzkdypm-qtbase-5.9.2/lib/libQt5Core.so.5
#48 0x00007ffff6833bba in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /nix/store/yxyg5dykv5s7hzvfdg1745zz2rzkdypm-qtbase-5.9.2/lib/libQt5Core.so.5
#49 0x00007ffff683c2c4 in QCoreApplication::exec() () from /nix/store/yxyg5dykv5s7hzvfdg1745zz2rzkdypm-qtbase-5.9.2/lib/libQt5Core.so.5
#50 0x00000000004155c4 in main ()

**Comment by kmkolasinski** [comment]
Do you have something in log.txt file?

**Comment by pmiddend** [comment]
Sadly, no. Just "libpng warning: iCCP: known incorrect sRGB profile", but that can't be the reason...

**Comment by kmkolasinski** [comment]
You are the first person trying to run AB on Nixos. I have no idea where may be the problem. Do you use prebuild binaries?

**Comment by pmiddend** [comment]
Yes, but I'll try compiling AwesomeBump myself. Keep this issue open, I will post my findings soon.

**Comment by pmiddend** [comment]
Okay, I will close this issue. After building the application myself, it works. I'll take this up to the NixOS people.

**Comment by kmkolasinski** [comment]
Wow, thank you! Glad you solved the problem.
