### ISSUE TITLE
./RunAwesomeBump.sh: 3: export: apps/AwesomeBump: bad variable name

### ISSUE THREAD

**Issue by harkoad** [kmkolasinski/AwesomeBump#135]
can anyone check! i think its a bug!!!!

**Comment by kmkolasinski** [comment]
I have no idea what are you trying to show with this issue? Maybe some description of your problem?

**Comment by harkoad** [comment]
well i try to run it from terminal like said but it will give me this error.

**Comment by kmkolasinski** [comment]
It would be nice to see your system specification.
