### ISSUE TITLE
The trouble with QtnPEG 

### ISSUE THREAD

**Issue by GentleHedgehog** [kmkolasinski/AwesomeBump#137]
I cloned this project and initialized the QtnProperty submodule in my Ubuntu 12.04. I try to build the project in Qt 5.8.0, but I get the following messages:

16:37:47: Выполняются этапы для проекта AwesomeBump...
16:37:47: Настройки не изменились, этап qmake пропускается.
16:37:47: Запускается: «/usr/bin/make» 
cd Sources/ && ( test -e Makefile || /opt/Qt5.8.0/5.8/gcc_64/bin/qmake -o Makefile /home/oleg/WORK/QtProjects/OpenGL/AwesomeBump/AwesomeBump/Sources/Sources.pro -spec linux-g++ ) && /usr/bin/make -f Makefile 
make[1]: Вход в каталог `/home/oleg/WORK/QtProjects/OpenGL/AwesomeBump/build-AwesomeBump-Desktop_Qt_5_8_0_GCC_64bit-Release/Sources'
/opt/Qt5.8.0/5.8/gcc_64/bin/qmake -o Makefile /home/oleg/WORK/QtProjects/OpenGL/AwesomeBump/AwesomeBump/Sources/Sources.pro -spec linux-g++
Project MESSAGE: *** Adding 'qtnproperty' module.
make[1]: Выход из каталога `/home/oleg/WORK/QtProjects/OpenGL/AwesomeBump/build-AwesomeBump-Desktop_Qt_5_8_0_GCC_64bit-Release/Sources'
make[1]: Вход в каталог `/home/oleg/WORK/QtProjects/OpenGL/AwesomeBump/build-AwesomeBump-Desktop_Qt_5_8_0_GCC_64bit-Release/Sources'
/home/oleg/WORK/QtProjects/OpenGL/AwesomeBump/AwesomeBump/Sources/utils/QtnProperty/bin-linux/QtnPEG /home/oleg/WORK/QtProjects/OpenGL/AwesomeBump/AwesomeBump/Sources/properties/Filter3DDOF.pef
/home/oleg/WORK/QtProjects/OpenGL/AwesomeBump/AwesomeBump/Sources/utils/QtnProperty/bin-linux/QtnPEG: error while loading shared libraries: libQt5Core.so.5: cannot open shared object file: No such file or directory
make[1]: Выход из каталога `/home/oleg/WORK/QtProjects/OpenGL/AwesomeBump/build-AwesomeBump-Desktop_Qt_5_8_0_GCC_64bit-Release/Sources'
make[1]: *** [/home/oleg/WORK/QtProjects/OpenGL/AwesomeBump/AwesomeBump/Sources/properties/Filter3DDOF.peg.cpp] Ошибка 127
make: *** [sub-Sources-make_first-ordered] Ошибка 2
16:37:48: Процесс «/usr/bin/make» завершился с кодом 2.
Ошибка при сборке/установке проекта AwesomeBump (комплект: Desktop Qt 5.8.0 GCC 64bit)
Во время выполнения этапа «Сборка»
16:37:48: Прошло времени: 00:01.

I checked an existence of libQt5Core.so.5 in /opt/Qt5.8.0/5.8/gcc_64/lib (it is link to libQt5Core.so.5.8.0).

**Comment by kmkolasinski** [comment]
It's not a problem with Qtn but rather with with Qt. Do you use build script?

**Comment by GentleHedgehog** [comment]
Yes, I had to do the work of the qtn extracompiler by hand. It didn't work until I set LD_LIBRARY_PATH in ~/.bashrc, but it hasn't worked at all yet when the make program runs it itself.

**Comment by kmkolasinski** [comment]
Sorry for stupid question, so does it mean that you have solved your problem or not?

**Comment by GentleHedgehog** [comment]
I partially solved this problem. Could you please advise me about the open gl version? Glxinfo gave me information that opengl version = 3.0, and glx max core profile version = 3.3, doesn't it allow me tu start AB?

**Comment by kmkolasinski** [comment]
It maybe related to opengl detected by Qt itself. Sorry, I don't think I can help you in such case, your graphics card seems to be to old.
