### ISSUE TITLE
Linux segfault

### ISSUE THREAD

**Issue by sirmaxim** [kmkolasinski/AwesomeBump#138]
Built on ArchLinux (correct Qt path is `/usr/bin/qmake-qt5`)

> Bin]$ ./AwesomeBump 
Starting application:
Application dir: "/ramdisk/awsomebump/AwesomeBump/Bin"
Data dir: "./"
libpng warning: iCCP: known incorrect sRGB profile
"Running the AwesomeBump 5.0 (2016)"
Checking OpenGL widget:
Widget OpenGL: "4.6"
Context valid: true
OpenGL information:
VENDOR: NVIDIA Corporation
RENDERER: GeForce GTX 970/PCIe/SSE2
VERSION: 4.6.0 NVIDIA 387.34
GLSL VERSION: 4.60 NVIDIA
First grunge map: "ground1.png"
First grunge map: "ground1.png"
First grunge map: "ground1.png"
First grunge map: "ground1.png"
First grunge map: "ground1.png"
First grunge map: "ground1.png"
First grunge map: "ground1.png"
First grunge map: "ground1.png"
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
Initialization: Build image properties
calling  virtual void GLImage::initializeGL()
Loading filters (fragment shader)
done
Loading filters (vertex shader)
done
FBOImages::creating new FBO( 256 , 256 ) with id= 1
FBOImages::creating new FBO( 1024 , 1024 ) with id= 2
FBOImages::creating new FBO( 1024 , 1024 ) with id= 3
virtual void GLImage::resizeGL(int, int)
  activeImage is null
Initializing 3D widget: detected openGL version: "4.1"
Loading quad (geometry shader)
done
Loading quad (vertex shader)
done
Loading quad (tessellation control shader)
done
Loading quad (tessellation evaluation shader)
done
Segmentation fault (core dumped)

**Comment by ryobg** [comment]
I got the same issue. So, I just went on with the pre-built binaries.

**Comment by kmkolasinski** [comment]
AB now support openGL core profile which may solve this problem.
Additionally this is new binary: https://github.com/kmkolasinski/AwesomeBump/releases/tag/Linuxv5.1

**Comment by macmv** [comment]
Still have the issue on 5.1, with prebuilt binaries, with either RunAwesomeBump.sh or RunAwesomeBumpGL330.sh
