### ISSUE TITLE
Pixel art maps

### ISSUE THREAD

**Issue by Hevedy** [kmkolasinski/AwesomeBump#14]
Is possible an option with add a check box or something to enable/disable the filter to view/generate maps to view the pixels and not the blur ?
Thanks.

**Comment by kmkolasinski** [comment]
Hi, do you mean some option which will on/off the texture filtering?

**Comment by Hevedy** [comment]
Yes that exactly what i talking about.
*And i got a problem with the 2.0 & 1.0 how turn on of the maps to view in the viewport only the selected maps or only the checked maps?

**Comment by kmkolasinski** [comment]
Texture filetring is quite simple problem, because there was already a similar issue before, I think I can do something you want. 
Currently you cannot turn off/on all the textures in the 3D viewport.  You can disable/enable only specular/normal and diffuse map.

**Comment by Hevedy** [comment]
Nice.
Will be nice if add the other maps that options, the main problem for me is the heightmap (all time in the viewport).

**Comment by kmkolasinski** [comment]
Hi, all the problems were solved in new version: http://awesomebump.besaba.com/
