### ISSUE TITLE
Support for Bent Normals

### ISSUE THREAD

**Issue by riccardogiorato** [kmkolasinski/AwesomeBump#143]
Is it possible to generate [Bent Normals](https://docs.unrealengine.com/en-us/Engine/Rendering/LightingAndShadows/BentNormalMaps) with the latest version of AwesomeBump?

Or we can only generate simple normals?

Is this feature planned in the future versions?

**Comment by kmkolasinski** [comment]
Hi, unfortunately Bent Normals are not supported.

**Comment by riccardogiorato** [comment]
Is it planned support for them?

**Comment by kmkolasinski** [comment]
Nope, I just try to keep this project alive but nothing more.
