### ISSUE TITLE
cannot open awesomebump

### ISSUE THREAD

**Issue by danimiras1111** [kmkolasinski/AwesomeBump#144]
Hello, i cant install the program, every time i try,  it appears this message,  is it possible to solve it?  I've Windows 7 x64. thanks!

Fatal Error!
Sorry but it seems your graphic card does nor support open gl 4.1
program will not run

MY SYSTEM INFORMATION:

OpenGL Version 2.1.2
GLSL Version 1.20 NVIDIA via Cg compiler
GeForce 610M/PCI/SSE2 - NVIDIA Corporation

Color Buffer: 32 bits double buffered
Depth Buffer: 24 bits
Stencil Buffer: 8 bits
Anisotropy: supported (max 16)

Features:
  - Multitexture: 1
  - Shaders: 1
  - Buffers: 1
  - Framebuffers: 1
  - BlendColor: 1
  - BlendEquation: 1
  - BlendEquationSeparate: 1
  - BlendSubtract: 1
  - CompressedTextures: 1
  - Multisample: 1
  - StencilSeparate: 1
  - NPOTTextures: 1
  - NPOTTextureRepeat: 1
  - FixedFunctionPipeline: 1

**Comment by kmkolasinski** [comment]
Hi, the error message is clear:
`Sorry but it seems your graphic card does nor support open gl 4.1`
You have old graphics card or drivers. AB requires minimum version of OpenGL to be 3.3 but you have 2.1.2.

**Comment by qwertychouskie** [comment]
You probably have very outdated graphics drivers.  Please download the latest drivers from Nvidia's website and try again.
