### ISSUE TITLE
Batch tool doesnt have setting to exclude maps

### ISSUE THREAD

**Issue by rjunrajput** [kmkolasinski/AwesomeBump#148]
How do I export only normal and diffuse textures with batch tool ? Also batch tool exports same texture at 2 different resolutions. 
Thanks

**Comment by kmkolasinski** [comment]
You can only export all textures in batch mode, and if you want different resolution you can try to change image resolution in settings tab and then run batch mode again.

**Comment by rjunrajput** [comment]
Thank you for reply. 
I hope we will have an option to disable maps in future version of AB.
