### ISSUE TITLE
Won't compile

### ISSUE THREAD

**Issue by foremancr** [kmkolasinski/AwesomeBump#149]
I have been trying to compile this in QT 4.9.0 and I get the following error:
d Sources/ && /home/foremancr/Qt/5.12.3/gcc_64/bin/qmake -o Makefile /home/foremancr/Desktop/AwesomeBump-Linuxv5.0/Sources/Sources.pro -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug
Cannot read /home/foremancr/Desktop/AwesomeBump-Linuxv5.0/Sources/utils/QtnProperty/PEG.pri: No such file or directory
Project ERROR: QtnProperty not found. Did you forget to 'git submodule init/update'
/home/foremancr/Desktop/build-AwesomeBump-Desktop_Qt_5_12_3_GCC_64bit-Debug/Makefile:39: recipe for target 'sub-Sources-qmake_all' failed
make: *** [sub-Sources-qmake_all] Error 3
13:39:53: The process "/usr/bin/make" exited with code 2.
Error while building/deploying project AwesomeBump (kit: Desktop Qt 5.12.3 GCC 64bit)
When executing step "qmake"

I looked into this directory and this file doesn't exist.  I'm not sure where to find this file

**Comment by kmkolasinski** [comment]
Hi, do you use unixBuildScript.sh to compile AB ?

**Comment by foremancr** [comment]
I go into QT 4.9.0 and select "AwesomeBump.pro and try to build it from there.  I create a build folder and this is where I get the errors

**Comment by kmkolasinski** [comment]
I think the best way to compile AB is to use this script, here is the instruction: 
https://github.com/kmkolasinski/AwesomeBump#unix-bash-automated-script

**Comment by foremancr** [comment]
I have set the path to the following and you can see the error.  I think
this is the path??

 ---------------------------------
      Error: Wrong Qt path.
 ---------------------------------
 Qt not found at 'usr/lib/x86_64-linux-gnu/qtchooser/default.conf'.
 Please set the MY_QT_PATH variable in the ./unixBuildScript.sh

foremancr@foremancr-desktop:~/Desktop/AwesomeBump-Linuxv5.0$

**Comment by kmkolasinski** [comment]
You have to set the right Qt path. In my case I have installed Qt in the home folder and my path is:  `/home/user/libs/Qt/5.8/gcc_64/bin/`

You can also try to search for available Qt paths with this command:
```
locate qmake | grep bin
```
For example,  I have another Qt installed at: `/usr/lib/x86_64-linux-gnu/qt5/bin`

**Comment by foremancr** [comment]
Thanks so much for the great help. It would be great to have a video on
installing this software for people like me which is new to this process

**Comment by kmkolasinski** [comment]
Hi, thanks for feedback, actually you could install AB with QtCreator, but it would require more expertise. I'm closing this issue.
