### ISSUE TITLE
Results of height map quite different from njobs and the normal map itself

### ISSUE THREAD

**Issue by stephen147** [kmkolasinski/AwesomeBump#154]
See attached a test that I've set up with the original normal map, njobs converted normal map, my attempt in photoshop and awesome bumps normal map to height map result.

Is there a way to achieve the same results as njobs map here?

No matter what settings I tried in awesome bump, I couldn't get the same result as njobs.

![test of 4 methods](https://user-images.githubusercontent.com/14054664/65606756-56c62400-dfa3-11e9-9ac1-67af798338c6.png)

**Comment by kmkolasinski** [comment]
Hi, could you send me the input diffuse image you used for this example and the expected njob normal map ?

**Comment by stephen147** [comment]
Hi, the map I'm using is the normal map itself to derive the height map.

Maybe it not primarily meant for that purpose? Is it possible to email them to you as they are rather large files 30mb for the normal map.

**Comment by kmkolasinski** [comment]
Yes, please send me them via mail awesomebump.help@gmail.com  (the source diffuse map and the expected normal map). I will check if I can get the same result (I will  be able to do this next week). If the images are large you can try to play with different settings by changing "details size" to large or huge. Example result with small details:
![image](https://user-images.githubusercontent.com/10145864/65687901-6c525100-e06a-11e9-8e75-53b8ec989dea.png)

Here I enabled larger details:
![image](https://user-images.githubusercontent.com/10145864/65687933-7ecc8a80-e06a-11e9-827f-345fbe7c42a4.png)

**Comment by kmkolasinski** [comment]
@stephen147  is this issue still valid ? I haven't received any pictures from you.

**Comment by stephen147** [comment]
I did send an email. Did you check your spam folder? It probably has auto-deleted by now.

I'll try to see if I have it in my outbox.

**Comment by stephen147** [comment]
These files were shared via wetransfer and they are now deleted as I checked the link from the email which was sent to you on the 27th Sept.

You can perhaps install njob to see how the differences are, as I've described.

**Comment by kmkolasinski** [comment]
You are right, I'm really sorry I didn't notice your mails somehow. Can you share this images again with me? I think I will have some time to check them this week.

**Comment by Calinou** [comment]
You should be able to upload files up to 50 MB on GitHub. Just stick them in a ZIP archive if GitHub complains about the format. If that still doesn't work, use [transfer.sh](https://transfer.sh/) for temporary large file uploads.

**Comment by stephen147** [comment]
I have deleted the max file and the others thinking you had received them. _I've got into the habit of deleting files and not hoarding them any more_. :)

I'll go get a map now and send it so you can convert them in njob and your app to see the difference.

**Comment by stephen147** [comment]
[](url)

**Comment by stephen147** [comment]
email sent.
