### ISSUE TITLE
"ABv5.1 Ubuntu 18LTE" link is broken (404 error)

### ISSUE THREAD

**Issue by Lissanro** [kmkolasinski/AwesomeBump#155]
On the main page https://github.com/kmkolasinski/AwesomeBump there are few links to binary releases, and first one ("ABv5.1 Ubuntu 18LTE") is broken.

Currently it points to https://github.com/kmkolasinski/AwesomeBump/releases/tag/Linuxv5.1 and this page does not exist.

I suggest to replace it with the link to https://github.com/kmkolasinski/AwesomeBump/releases/tag/Linuxv5.1.1 .

**Comment by kmkolasinski** [comment]
Wow @Lissanro thanks a bunch! Links are fixed now.
