### ISSUE TITLE
Supply a compiled version

### ISSUE THREAD

**Issue by LukeOnuke** [kmkolasinski/AwesomeBump#160]
As a python programmer and a C# beginner compiling is realy intimidating to me and some people may not know how to do it so perhaps make a COMPILED folder with the compiled exe

**Comment by Calinou** [comment]
> so perhaps make a COMPILED folder with the compiled exe

Including compiled binaries (and generated artifacts in general) in Git is considered bad practice. Instead, GitHub's releases mechanism should be hosted to host binary releases ([as is already done](https://github.com/kmkolasinski/AwesomeBump/releases)).
