### ISSUE TITLE
UI Scaling

### ISSUE THREAD

**Issue by y0nd0** [kmkolasinski/AwesomeBump#163]
I can't read anything. The font / UI is too small. It does not respect the UI scaling of the OS. I just using a regular 4k resolution with 200% UI scaling. 
We could add an option in config.ini. But the best solution is to use the OS setting. I have no dev experience with this feature. Any ideas?

**Comment by y0nd0** [comment]
Related: #131

**Comment by kmkolasinski** [comment]
Hi, have you try to increase font size here: https://github.com/kmkolasinski/AwesomeBump/blob/Release/Bin/Configs/gui.ini
and restart the program.

**Comment by y0nd0** [comment]
Yes, this is much better. Thanks.
