### ISSUE TITLE
Some issues

### ISSUE THREAD

**Issue by mifth** [kmkolasinski/AwesomeBump#17]
Hi.

I tried to load my normal map but i got artifacts.

Screenshot:
![cache0](https://cloud.githubusercontent.com/assets/2251298/6266576/6ae8ff1c-b84c-11e4-81ee-7a5a41f6a01a.png)

File:
![normal](https://cloud.githubusercontent.com/assets/2251298/6266573/6400f3a8-b84c-11e4-9ea5-28e939938304.png)

Also i found some issues:
- No "File->New" button in the menu. It's useful.
- Is it possible to generate occlusion and specular based only on NormalMap? For example, i baked normal map in blender, but occlusion and specular would be great to generate in AB. 
- Is it possible to switch color texture off? For example, if i load only normal map.

Thanks.

**Comment by mifth** [comment]
Another issue:

If i load the texture at the first post as Diffuse and as Height textures - i'll get different textures scale.

Here is the screenshot:
![cache0](https://cloud.githubusercontent.com/assets/2251298/6266697/e68abfb0-b84d-11e4-9dd4-13313b381136.png)

**Comment by Hevedy** [comment]
- Looks like a problem by the different size of the textures.
- I think you cannot create a specular from normal, because are different maps, anyway, why no load the normal as diffuse and generate the other maps ?
- Color texture off ? you speak about turn off the diffuse map ?, if you go to the 3D Settings with the last version, you have a buttons to turn off/on the different maps.

**Comment by mifth** [comment]
Hi Hevedy.

About different size:
I loaded the same texture into Diffuse and Height. AB changes sizes if it happens. Just take my normal map and put it into the Diffuse and into the Height. And you'll get this issue.

About spacular/occlusion based on NormalMap:
ShaderMap app can do it. Here is my test http://youtu.be/mE36N8W5PKg
I have old version 1.0. But 2.0 can do this too i guess. I think CrazyBump can do it too.
It's very good workflow - based on normal map.

About color texture switching off: thanks, i'll check it.

**Comment by Hevedy** [comment]
Yeah, i get that problem with one of my textures.

About the specular, yeah that create the map but i think that is useless because the specular map is for light reflections, and you are creating reflections using reliefs of the normal, anyway I suppose this could be added.

**Comment by mifth** [comment]
I use normalmapToSpecular to generate occlusion/dirt map. Then i apply such a map to color. It's good to make such maps.
DDO makes such maps based on normalmap. 
http://quixel.se/ddo - the app
http://quixel.se/sites/default/files/imagesddonew/ddo_stylized_orc.jpg - texture with applied occlusion/dirt maps which were made based on NormalMap.

**Comment by kmkolasinski** [comment]
Hi, AB is designed to work with images with the same dimensions. If you generate textures from diffuse image AB automaticaly resize all textures to size of the diffuse texture. This is not happen in case when you load the normal map or other textures. You have to resize all textures by yourself - in order to do that you can use the Image Resize tool in settings tab. So basically in your case if you want to start with normal image you can follow this movie:
https://www.youtube.com/watch?v=aXd6aznXmZI&feature=youtu.be
(sorry I used your texture in movie )

**Comment by mifth** [comment]
Hi!
Thanks for the video. Very useful.
I have this issue: http://youtu.be/GFNz8uCLcrE
I just load diffuse and height. I suppose that there should be no problems with resize. But it happens.

**Comment by kmkolasinski** [comment]
Hi, if you open the image AB does not resize rest images automatically. So if you loaded diffuse and height textures, the rest (occlusion, normal and specular maps) have still same default size (in your case 512x512). Use the resize button, it is necessary to have images with same size in AB. 

I will think about "File->New" feature.

**Comment by mifth** [comment]
@kmkolasinski but artifacts are in the preview of the height and diffuse. Diffuse is ok but height will not be in a correct size. Please check my video again and see the 3d viewport.

Actually i can't understand why i should resize something. All apps do it automatically. Is it possible to make it in the same way?

**Comment by mifth** [comment]
I mean when i load the same texture into Diffuse and height - i get such a result in 3d viewport https://cloud.githubusercontent.com/assets/2251298/6266697/e68abfb0-b84d-11e4-9dd4-13313b381136.png

**Comment by kmkolasinski** [comment]
Ok, I see your problem. Maybe you are right all images should be resized to size of loaded image. Currently AB does support this feature so you must cope somehow with it. In your case the solution  is: resizing all images to desired size just after loading the image.

**Comment by mifth** [comment]
Thanks a lot for confirmation the issue. I'll try doing like you said.

**Comment by kmkolasinski** [comment]
Issue solved in version 3.0
