### ISSUE TITLE
Support of software for Win11

### ISSUE THREAD

**Issue by ghost** [kmkolasinski/AwesomeBump#171]
Add support of software for Win11

**Comment by Calinou** [comment]
AwesomeBump should already work on Windows 11, provided your GPU has sufficient OpenGL support (OpenGL 4.3 or later).

In general, if something works on Windows 10, it'll work on Windows 11 as well. Windows is very good at backwards compatibility (more so than macOS and Linux, aside of the rare exception).

**Comment by ghost** [comment]
I checked. Works.
