### ISSUE TITLE
OBJ file is not loaded

### ISSUE THREAD

**Issue by mifth** [kmkolasinski/AwesomeBump#18]
Hi.

I tried to load a simple obj file from blender but i failed.

![cache0](https://cloud.githubusercontent.com/assets/2251298/6266892/e08d9c70-b84f-11e4-99ae-1aa4add22ee5.png)

Here is the file:
https://dl.dropboxusercontent.com/u/26887202/AwsomeBump/temp.zip

**Comment by Hevedy** [comment]
Please you can show me your export settings ?

**Comment by mifth** [comment]
Oh!!! It seems it's imported! My model had no UVs. I have to unwrap the model and create new UVs.
![cache1](https://cloud.githubusercontent.com/assets/2251298/6268204/250b3b30-b85c-11e4-9f3f-87cfe9f05cd0.png)

Could you add UVs checking during importing?

**Comment by Hevedy** [comment]
Keep the issue open, i'm sure when @kmkolasinski have time will check your request.

**Comment by mifth** [comment]
Ok.

**Comment by kmkolasinski** [comment]
Hi, see the log file after each error you encountered. Didn't you get the error message? (I did the experiment with suzanne)
![monkeyerror](https://cloud.githubusercontent.com/assets/10145864/6392494/732eea7c-bdc1-11e4-9f37-3d5f17d235ab.png)
In log file there are lines:
[2/2015 14:10:21] {Debug} 		 Warning. Shape i= 0  with name:  "Suzanne"  has no texcoords.
[26/02/2015 14:10:21] {Debug} 		 Error. Mesh has no vertices or normals or UVs, so it cannot be loaded.

**Comment by mifth** [comment]
I saw only popup message.

**Comment by kmkolasinski** [comment]
I will add more info in popup message.

**Comment by mifth** [comment]
Great, thanks.

**Comment by kmkolasinski** [comment]
I'm closing this issue.
