### ISSUE TITLE
fails to compile 

### ISSUE THREAD

**Issue by blurymind** [kmkolasinski/AwesomeBump#19]
Manjaro linux (arch based) - 64 bit.latest version 2.1 and also tried with trunk version. I follow your video tutorial and I get this error message in qt creator:

>.....
>./AwesomeBump-master/formsettingscontainer.cpp:71:63: warning: unused parameter 'field' [-Wunused-parameter]
 void FormSettingsContainer::reloadSettings(FormSettingsField* field){
                                                               ^
/usr/lib/qt/bin/rcc -name content ../AwesomeBump-master/content.qrc -o qrc_content.cpp
RCC: Error in '../AwesomeBump-master/content.qrc': Cannot find file 'content/Capsule.obj'
Makefile:666: recipe for target 'qrc_content.cpp' failed
make: *** [qrc_content.cpp] Error 1
23:50:37: The process "/usr/bin/make" exited with code 2.
Error while building/deploying project AwesomeBump (kit: Desktop)
When executing step "Make"
23:50:37: Elapsed time: 01:34.

**Comment by kmkolasinski** [comment]
Hi, try the new commit.

**Comment by kmkolasinski** [comment]
Hi, do you have still problems with compilation?

**Comment by blurymind** [comment]
sorry, I noticed that my card doesnt support opengl 4^, so there is no point in compiling it anymore. :)
I can try compiling it, but it will probably crash my computer if I try running it.

**Comment by kmkolasinski** [comment]
ah, sorry to hear that. I'm closing this issue in that case.
