### ISSUE TITLE
Running AwseomeBump crashes the display driver

### ISSUE THREAD

**Issue by Lamoot** [kmkolasinski/AwesomeBump#20]
When I run AwesomeBumpV2.1Bin32x64Win7 the application becomes unresponsive and I get a notification that the display driver has stopped working and then recovered. The log doesn't complain of a bad OpenGL version (4.2). 

Link to the log:
http://www.pasteall.org/57045

I'm on Win 7 64bit
Mobility Radeon 5650

It could be a bug in my installed drivers, but usually everything works fine here and I have never experienced a driver crash before.

**Comment by kmkolasinski** [comment]
Hi,
Did you tried previous AB versions ? In 2.1 tessellation was added so relatively new graphics card is required. Can you find your driver on this page?
http://feedback.wildfiregames.com/report/opengl/device/Mobility%20Radeon%20HD%205650
This topic is really not promising:
http://superuser.com/questions/723389/opengl-4-software-with-ati-mobility-radeon
How old is this graphics card? 2010?  First version of openGL 4.0 was introduced in 2010 (according to http://en.wikipedia.org/wiki/OpenGL#OpenGL_4.0), so I there maybe a problem with drivers.

**Comment by Lamoot** [comment]
AB 2.0 opens properly, the interface works, but the image and 3d view only show a black mesh/texture.
AB 1.0 opens properly and I can open and manipulate images as intended.

I can't find my driver on the wildfire page. Here it says says it's OpenGL 6.14.10.12217 version. It's a 13.4 catalyst version, meaning roughly 2 years old.

The graphics card is from from 2010 (release january 7 2010).
http://www.notebookcheck.net/ATI-Mobility-Radeon-HD-5650.23697.0.html

**Comment by kmkolasinski** [comment]
Hard to say It potentialy looks like drivers problem which means your card may not support some of the openGL 4.0 functions which AB uses in recent versions, so probably I will not able to help you. Do you have any suspicious messages in log file from 2.0 version?

**Comment by Lamoot** [comment]
I'll try to install a more recent driver in the near future and see if the problem is still there. Would be nice if it worked here, but I'm aware that my graphics card might not be enough anymore.

Here's the 2.0 log, it says the fragment shader failed to compile.
http://www.pasteall.org/57075

**Comment by kmkolasinski** [comment]
Ok, there was a bug a 2.0 version which caused problems on some graphics cards. 
I fixed this problem. Can you try to download 2.0 version again?

**Comment by Lamoot** [comment]
I tried 2.0 version again from this link https://github.com/kmkolasinski/AwesomeBump/releases/download/Winx32v2.0/AwesomeBumpV2.0Bin32x64Win7.zip

I get the following error. The program loads fine, the material/texture are still black.
http://www.pasteall.org/57078

**Comment by kmkolasinski** [comment]
Ok, there were two bugs. Please try again.

**Comment by Lamoot** [comment]
The new 2.0 version works properly. It loads and displays the textures. The log also doesn't mention any errors. Thank you for the fix. 

For 2.1 I can come back to you once I test other drivers. I won't be able to do this immediately, as I don't wish to potentially screw up my driver installation and not be able to do any work in the next few days.

**Comment by kmkolasinski** [comment]
Ok. First of all see all the differences on YT between 2.1  and 2.0 and make sure if it is worth to spend many hours for few upgrades.
