### ISSUE TITLE
Doesn't compile on Debian

### ISSUE THREAD

**Issue by jhaiduce** [kmkolasinski/AwesomeBump#22]
When I try to build on Debian Testing (Jessie), I get an error. This is using Qt 5.3.2. It builds successfully on Fedora 21 using Qt 5.4.0, so I'm guessing the problem is caused by API differences between QT versions.

Specifically, the error is this:

../AwesomeBump/formsettingscontainer.cpp: In member function 'void FormSettingsContainer::removeSetting(FormSettingsField*)':
../AwesomeBump/formsettingscontainer.cpp:66:18: error: 'class QVector<FormSettingsField*>' has no member named 'removeOne'
     settingsList.removeOne(field);
                  ^

**Comment by Simmesimme** [comment]
I encountered the same issue and replaced the erroneous line with

`settingsList.remove(settingsList.indexOf(field));`

which seems to do the trick.

**Comment by kmkolasinski** [comment]
Cool! Thank you! If you forked my repo, you can make a pull-request with your change otherwise I will do it this evening.

**Comment by kmkolasinski** [comment]
removeOne() is since Qt 5.4. I commited your version.

**Comment by jhaiduce** [comment]
Thanks guys!
