### ISSUE TITLE
Cannot load basic models like cube

### ISSUE THREAD

**Issue by Posiek** [kmkolasinski/AwesomeBump#23]
Hi, I can't preview my texture on basic models like plane, cude etc. Any advice how can I do that?

![issue](https://cloud.githubusercontent.com/assets/1121756/6637701/f868b4d0-c97d-11e4-9707-a9a12b455325.jpg)

**Comment by Posiek** [comment]
Well, I copied the models folder to build folder and now everything is all right..

**Comment by kmkolasinski** [comment]
Hi, there is another way to solve your problem: just set the "working directory" in the project settings to the AB source folder.
