### ISSUE TITLE
Cannot even build projct

### ISSUE THREAD

**Issue by MikeM2** [kmkolasinski/AwesomeBump#24]
I am using Windows 7 and trying to build AwesomeBump
This shows up:
![capture](https://cloud.githubusercontent.com/assets/10091113/6641182/adbec1d2-c972-11e4-9fc6-49e155cf71fe.JPG)
I tried "adding kits," but I don't have a clue what it means by that. I have NO idea what to do next.
Please help!!

**Comment by Hevedy** [comment]
You need the x32 or x64 build with OpenGl from Qt website/installer.

*You have a compiled version in the releases (https://github.com/kmkolasinski/AwesomeBump/releases)

**Comment by MikeM2** [comment]
Thanks. Could you by any chance send me a direct link to the x32 (or x64 )build with OpenGl from Qt website/installer? 
I'm serious when I say I really have NO IDEA what I am doing now, since following the instructions on building AwesomeBump did not work.

**Comment by MikeM2** [comment]
Wait, duh, never mind, you just did

**Comment by Hevedy** [comment]
Here you go: http://www.qt.io/download-open-source/#section-2
http://download.qt-project.org/official_releases/qt/5.4/5.4.1/qt-opensource-windows-x86-msvc2013_opengl-5.4.1.exe

*You need first VS installed:
https://www.visualstudio.com/
http://go.microsoft.com/?linkid=9863608

**Comment by MikeM2** [comment]
Whoa! Thanks alot!
