### ISSUE TITLE
Doesn't recognize correct GPU on Hybrid Notebook (Nvidia Optimus)

### ISSUE THREAD

**Issue by RaphaBarros** [kmkolasinski/AwesomeBump#27]
I'm on Ubuntu 14.04 64-bits, using 331.38 (not using a newer version because it screws Cycles in Blender, but this driver version supports OpenGL 4.4), and when I try to run AwesomeBump, the following message appears:

"Fatal Error!
Sorry but it seems that your graphics card does not support openGL 4.0.
Program will not run :(
See log.txt file for more info."

And the logs is like this:

[27/03/2015 18:46:43] {Debug} 		 Starting application:
[27/03/2015 18:46:43] {Debug} 		 "Running the AwesomeBump v3.0"
[27/03/2015 18:46:43] {Debug} 		 Checking OpenGL version...
[27/03/2015 18:46:43] {Debug} 		 Widget OpenGL:  3 . 0
[27/03/2015 18:46:43] {Debug} 		 Context valid:  true
[27/03/2015 18:46:43] {Debug} 		 OpenGL information: 
[27/03/2015 18:46:43] {Debug} 		 VENDOR:  Intel Open Source Technology Center
[27/03/2015 18:46:43] {Debug} 		 RENDERER:  Mesa DRI Intel(R) Haswell Mobile 
[27/03/2015 18:46:43] {Debug} 		 VERSION:  3.0 Mesa 10.1.3
[27/03/2015 18:46:43] {Debug} 		 GLSL VERSION:  1.30
[27/03/2015 18:46:43] {Debug} 		 Version: 3
[27/03/2015 18:46:43] {Debug} 		 Error: AwesomeBump does not support openGL versions lower than 4.0 :(

And it doesn't matter if I try opening it using primusrun or optirun (To use Nvidia's GPU), the messages and logs are always the same, so I suppose it's not recognizing my GPU correctly.

Thank you.

**Comment by kmkolasinski** [comment]
Hi, very strange: the message tells: "VENDOR: Intel" so AB is starting with Intel GPU, which is not supported. You have to force somehow AB to use NVIDIA instead of Intel. Do you have NVIDIA control Panel Application?
Do you have installed Qt Creator?

**Comment by RaphaBarros** [comment]
Yes, I have Nvidia Control Panel and there I can set Nvidia as the default GPU, but I'm not sure how it'd work with the Bumblebee driver (which gives me the power to set which apps should run with Nvidia and which ones with Intel, by using primusrun or optirun command, sadly, both of them fail with AB and it doesn't recognize my Nvidia gpu) if I changed to Nvidia as default, aside from making my notebook waste more electric energy, of course xD. I'm also kind of traumatized with so many problems in Linux coming from bad drivers.

I don't have Qt Creator, but do you think I should try compiling AB myself to see if it works?

Thx again!

**Comment by poVoq** [comment]
Same issue here (also using Bumblebee). Maybe just add a command line parameter that allows you to just bypass the OGL check?

**Comment by kmkolasinski** [comment]
Guys, This seems to be a problem with Qt not AB. AB uses standard Qt functions to determine the created openGL context version, so it means the Qt does not detect proper GPU or maybe Bumblebee makes it confused. I don't know. Can you download the Qt Creator and compile the source code on your computers?  
You will probably need this: http://stackoverflow.com/questions/15143011/how-can-i-use-bumblebee-and-qtcreator-together/15143012#15143012

If you want to bypass openGL check see the main.cpp file there are few lines (there is a "if" instruction):
 if(!checkOpenGL()){
you can change it to
 if(false){
so that it will never get to the "if"

But, I'm not sure if it will help.

**Comment by RaphaBarros** [comment]
Sorry for the lack of response, but I tried the 4.0 beta version, and by changing the 5th line from RunAwesomeBump.sh file, from "./AwesomeBump" to "primusrun ./AwesomeBump" (I guess it'd also work with optirun) it's working fine now!

Thx a lot! This app will help me a lot in my university graduation project  :)

**Comment by kmkolasinski** [comment]
Great thanks for info :)

**Comment by poVoq** [comment]
*facepalm* now that was a lot easier than expected. Can confirm, works with "optirun -b primus ./Awesome..."
