### ISSUE TITLE
Windows release “zip bomb”

### ISSUE THREAD

**Issue by Calinou** [kmkolasinski/AwesomeBump#30]
When you extract the Windows release directly (using 7-Zip “Extract here…”), something called a “zip bomb” happens: all files are thrown into the directory you are extracting AwesomeBump in. This is undesired behaviour.

Please, put all files in a folder called AwesomeBump, then compress that one.

**Comment by kmkolasinski** [comment]
Hi,
I think this is not necessary:
1) You can always choose using 7-Zip option "Extract to AwesomeBump...." which will always create new folder for packed files. 
2) One may always see the content of the zip file without unpacking it, so if one expect the  "zip bomb" (which for me is totaly different thing) then one may create a folder before unpacking it.
