### ISSUE TITLE
Baking maps from high resolution models

### ISSUE THREAD

**Issue by Terrance8D** [kmkolasinski/AwesomeBump#32]
This is a feature request. There is a program called xNormal that bakes normal maps from high-resolution meshes, and it does it very well. There is another program called Knald that does this too. Would this be a difficult feature to implement?

**Comment by kmkolasinski** [comment]
For unwrapped UVs it should be easy as one know where to put each normal on texture, but for not unwrapped mesh I don't even know where to start... 
There are another drawbacks:
1) AB 3D view is totally not optimized, when you enable tessellation it dramatically slows down, high resolution meshes will probably crash this poor program :)
2) AB is free alternative for commercial programs, but xNormal is also free and it does it already, so why do you come with this request? What is the motivation for that?

**Comment by Terrance8D** [comment]
xNormal seems to only  run on Windows, Knald runs on Windows and Mac but costs $200 for the studio license. Blender can also do this, but I thought that it'd be neat to have this as part of a workflow.:)

**Comment by kmkolasinski** [comment]
Ok, I understand now. As I said when the model has already prepared UVs this should be easy. I will think about this.

**Comment by Hevedy** [comment]
You can paint over the 3D model and bake the textures in the blender.
I think that is very different to the AB purpose.
Anyway, if you decide add this, will be better divide the AB in different apps or different parts.
(Texture Maps editor & generator | Texture Edit | Models Maps Bake | Model viewer )

**Comment by kmkolasinski** [comment]
Don't worry, I just said that I will "think" about this :)
I would like to keep AB as simple as possible. The idea of AB is image processing nothing else, so I put efforts to optimize this part of the code. Code responsible  for 3D rendering is totaly not optimized (e.g. tessellation cracks ;) ) so as I said before high resolution meshes may be a problem. BUT: If normal baking does not require huge amount of work, and if it will not destroy the logical structure of the program, this functionality may be added, why not. (recently I've added a new feature - Low Frequency Filter, as a "feature request" from the user, I didn't have this tool in my plans but it took me one hour to implement... -- I have some experience with baking textures from meshes, so adding a small button e.g. "recalculate normals from mesh" would be a nice feature in AB). 

Thats why I said I will think about this: I need to estimate the effort which is required to make such feature to work with AB or if this really necessary as Blender already has this feature.

**Comment by Hevedy** [comment]
OKay but for what like this @Terrance8D ? 
Only for Normals or for (AO+Normals+Displacement+Albedo+Vertex Colors) ?

**Comment by kmkolasinski** [comment]
No more than normals. I have other plans for future releases.

**Comment by Hevedy** [comment]
@kmkolasinski "I have other plans for future releases." that sound badass... :)

**Comment by kmkolasinski** [comment]
Ops, of course I meant: I have already plans (TODO list) what features add or improve in AB, so I want to do them first, because I would be nice to finish what I've started already rather than starting another things. Sorry for confusion :)

**Comment by Hevedy** [comment]
@kmkolasinski no no, badass as say "with what going to surprise me the next time" ;)
More or less like a joke, sorry for the confusion xD

**Comment by kmkolasinski** [comment]
Ok, I did the reasearch and the baking normal map feature is no possible with AB. The AB pipeline just does not fit with some kind of calculation. I can't do this easily.
