### ISSUE TITLE
Poor performance on Manjaro

### ISSUE THREAD

**Issue by lordekeen** [kmkolasinski/AwesomeBump#37]
Hello, i've compiled Awesome Bump today from git, and wen i execute the program the 3d viewport is black and the whole program is very laggy, i'm using the last Manjaro (Arch based), on the logs the program show only libpng errors related to sRGB (i have all libpng installed)

**Comment by Robert42** [comment]
I had the same issue (Antergos, also Arch based). Have you tried compiling it using the `linuxBuildScript.sh` file?

**Comment by kmkolasinski** [comment]
Hi, current version of AB may be not stable. I still did not pushed new fixes which I have on my personal computer. Did you try previous versions of AB? 
e.g. this one: https://github.com/kmkolasinski/AwesomeBump/releases/tag/Linuxv3.0.4
BTW:  libpng errors  sound like problems with libraries not with AB. Do you have the lastest version of Qt? And did you try binaries from link above?

**Comment by lordekeen** [comment]
Robet42 i don't know about this script, i'll try to compile the previous versions. I have the lastest Qt avayable in the Aur repos, i'll also reinstall libpng to see if this fix the errors.

**Comment by Robert42** [comment]
@lordekeen I hadn't to install any aur packages i am aware of.

This script is the root directory of the project. But you  might also try to execute the binary with the /Bin directory as workingdir

**Comment by lordekeen** [comment]
The linuxBuildScript.sh worked (using the version 3.0.4 of AB), the only problem is my mouse get stuck when i try to rotate the 3d view.

**Comment by Robert42** [comment]
I have contributet a [pull request](https://github.com/kmkolasinski/AwesomeBump/pull/36) for something, which sounds quite similar.
Have you already tested the newsst version using the linuxBuildScript.sh with the newest AwesomeBump version?
