### ISSUE TITLE
Vertical tabs not readable on laptop screen resolutions like 1366x786

### ISSUE THREAD

**Issue by poVoq** [kmkolasinski/AwesomeBump#40]
While the program runs fine on my laptop, there is the slightly annoying fact that all the vertical tabs writing is shown like "D...e" or "Oc...en" etc.
I think qt does this because the vertical screen resolution is too low, but I guess having the first couple of letters would be easier to read.
The hover pop-up helps, but it is not consistently shown on the vertical taps for some reason. I think it only works on the first two vertical taps or so.

**Comment by kmkolasinski** [comment]
Hi, thanks for info, but did you try to change font size?

**Comment by poVoq** [comment]
No. Is there a way to do it in the program? But it is already 7 or 8, so really tiny as far as I can tell.

**Comment by Terrance8D** [comment]
Yep, it's in the output tab near the bottom.

**Comment by poVoq** [comment]
ok, well the smallest is 8, and the problem still exist then, just a bit less.

**Comment by kmkolasinski** [comment]
Could you send me some screenshot of your desktop? I would like to see the scale of the problem. If you have any suggestions how to fix this problem, please share with me.

**Comment by poVoq** [comment]
sure:
http://imgur.com/ncrqCjs

**Comment by kmkolasinski** [comment]
Thanks, I will try to add the scrollareaWidget to the left panel with tabs, otherwise (if this will not help) maybe some abbreviations instead full names will be enough.

**Comment by poVoq** [comment]
Just noticed that if I switch to the "oxygen" GUI style it works fine (on KDE5). So I guess no need to fix this,
