### ISSUE TITLE
Can't Import Large Image

### ISSUE THREAD

**Issue by DeathTBO** [kmkolasinski/AwesomeBump#43]
I am trying to import a massive image. It's a 77.7MB PNG file, and the resolution is: 10800 x 5400
However, when I import it it only shows a completely black image. I am using version 4.0, and I am running Windows 7 x64 Professional.

**Comment by kmkolasinski** [comment]
Hi,
Can you send you the log file and the image? Maybe your GPU does not have enough memory for it?

**Comment by DeathTBO** [comment]
I have an AMD r9 270x 2GB.

Image: https://www.dropbox.com/s/b1dixu8wg7yafmj/Earth_Color.png?dl=0

Log: https://www.dropbox.com/s/xmhfcy0vlhasj8t/log.txt?dl=0

**Comment by kmkolasinski** [comment]
And what about smaller images? do they work for you?

**Comment by DeathTBO** [comment]
Yes, they work perfectly fine.

**Comment by kmkolasinski** [comment]
I suppose that the image you tried to open is too big and there is not enough memory on your GPU. 
AB consumes a lot of memory in case of large images. You can simply calculate the minimum memory usage: each texture in AB is stored in GL_RGB16F format, which is 16bits per component. One pixel RGBA needs 16 * 4 / 8 =  8 bytes. If the image is of dimension: 10800x5400 you need  (10800x5400x8)/1024/1024 MB ~ 444MB! And this is for one texture. In AB you have 8 (plus other like grunge or material + others). So you need like 5GB on your GPU to deal with that texture.


PS: For future debug: In the log file you sent me  there are number of errors, which I don't have on my NVIDIA GPU.  Could you send me one more log from situation when program worked fine. Some day I will test AB on ATI GPU and I will try to remove all those errors.

**Comment by DeathTBO** [comment]
Thanks for your help. Kind of a shame that I need such a large amount of memory. I will just have to shrink the size.

Here is another log: https://www.dropbox.com/s/xmhfcy0vlhasj8t/log.txt?dl=0

On a side note, the memory information in the bottom left does not work (for AMD at least).

**Comment by kmkolasinski** [comment]
Ok, thanks for the log.
