### ISSUE TITLE
Strange behavior when running from a shortcut

### ISSUE THREAD

**Issue by lordekeen** [kmkolasinski/AwesomeBump#46]
So i've created a desktop shortcut (in Linux) to run AwesomeBump executable file, the problem is: when i run the program using the shortcut, the 3d area is completely black, no 3d at all, BUT if i open the folder where the program is located an run the executable directly, everything work normal.
Any clues in how to fix this?

**Comment by Terrance8D** [comment]
Try running the desktop shortcut from the terminal and see what kind of output there is.

**Comment by lordekeen** [comment]
I've copied the exec path from the desktop shortcut (in my case is /opt/awesomebump/AwesomeBump) and executed it in terminal.
The program runs as if I've just double clicked the desktop shortcut, without any 3D showing of, and no error output in terminal, BUT it shows an error when i try to load any mesh:
Loading mesh file failed: Core/3D/"nameofthemesh"

Looks like when i dont run the program directly in the folder, it cant find the necessary paths.

**Comment by baccenfutter** [comment]
Educated guess:
Create a wrapper script (let's say: /usr/local/mywyawesomebump)and in there first cd into the AwesomeBump working directory and then execute the binary. You have to be root to write a script into that location but then it will be available in your $PATH and you should be able to just say (# myawesomebump). Don't forget to make the script executable!

**Comment by lordekeen** [comment]
baccenfutter solution solved the problem, thanks!

**Comment by kmkolasinski** [comment]
Thanks @baccenfutter :)
