### ISSUE TITLE
Make wiki editable by everyone

### ISSUE THREAD

**Issue by Calinou** [kmkolasinski/AwesomeBump#48]
I plan to write various tutorials for AwesomeBump. How about making the wiki editable by everyone?

**Comment by kmkolasinski** [comment]
Sure not problem! Thank you @Calinou. But I think it will be better to allow to edit wiki only for collaborators, so I will make you a collaborator. I have planned to move all the website here on github after summer when I will have more time. 
PS: Please let me know if you can edit wiki now.

**Comment by Calinou** [comment]
> PS: Please let me know if you can edit wiki now.

Yes, I can edit the wiki.

**Comment by Calinou** [comment]
We might make a separate issue, that contains the list of documentation to migrate to the wiki. Such as, compiling AwesomeBump.

**Comment by kmkolasinski** [comment]
Great idea, the list will be very useful for sure.
