### ISSUE TITLE
AwesomeBump isn't pixel-perfect

### ISSUE THREAD

**Issue by makklaski** [kmkolasinski/AwesomeBump#6]
Can be tested by making a very crisp texture. By drawing some black strokes in MS Paint for example.
Use this crisp texture to generate normal map, height map, etc.
Save images.
I can see that lines in diffuse texture are a little bit blurry.
Even if Sharpen/Blur in diffuse tab is 0 and Reset Transform was clicked.

**Comment by kmkolasinski** [comment]
Hi, thank you for your feedback. 
This is because AB by default uses the linear interpolation for texture filtering, but you are right this should be disabled in order to preserve input image unchanged at the end.
I just fixed this issue.
Regards,
KK

**Comment by makklaski** [comment]
Hello.
Linear interpolation is good for quality.
It should not be a problem as long as pixel centres of a render target exactly match pixel centres of a drawn quad.
As described here for Direct3D 9 http://msdn.microsoft.com/en-us/library/windows/desktop/bb219690%28v=vs.85%29.aspx (of course in OpenGL half-pixel offset is not required)

I believe there is some float rounding issue or something. Some values are not exactly -1, zero or 1 but 0.989 or something, or render target size doesn't match drawn texture size, just my guess.

**Comment by kmkolasinski** [comment]
You are right, but I save displayed 2D textures directly to png/jpg image, thus if 2D texture is blured because of filtering reasons the output image will be also. Changing filtering type form LINEAR to NEAREST solved this problem.

**Comment by kmkolasinski** [comment]
Unfortunately, I was forced to come back to the LINEAR filtering. NEAREST mode was leading to aliasing problems in some cases, for example during rotation of the texture.
