### ISSUE TITLE
Can't compile with latest QT

### ISSUE THREAD

**Issue by baroquedub** [kmkolasinski/AwesomeBump#65]
I found that only the older version of QT (with the Desktop Qt 5.4.2 MinGW 32 bit) kit compiles successfully for me. The newer version (5.5.1) fails with the following errors:

J:\_BLENDER Projects\_TOOLS\AwesomeBump-Winx32v3.1.4\AwesomeBump-Winx32v3.1.4\Sources\glwidget.cpp:-1: error: undefined reference to `_imp__glGetError@0'

J:\_BLENDER Projects\_TOOLS\AwesomeBump-Winx32v3.1.4\AwesomeBump-Winx32v3.1.4\Sources\main.cpp:-1: error: undefined reference to `_imp__glGetError@0'

J:\_BLENDER Projects\_TOOLS\AwesomeBump-Winx32v3.1.4\AwesomeBump-Winx32v3.1.4\Sources\main.cpp:-1: error: undefined reference to `_imp__glGetString@4'

:-1: error: ./release\main.o: bad reloc address 0x4 in section `.text.startup'

collect2.exe:-1: error: error: ld returned 1 exit status

**Comment by kmkolasinski** [comment]
Why do you compile 3.14 version not the lastest one?

**Comment by baroquedub** [comment]
Simply because I saw v4.0 refered to as a beta :)

**Comment by CodePhase** [comment]
I'm under the impression all software in this project is pretty much in a beta stage.  A lot has changed since the 3.14 release.

**Comment by kmkolasinski** [comment]
Not a beta,  rather code written fast but bad !
