### ISSUE TITLE
Program incorrectly tries OpenGL 4.0 not 3.30

### ISSUE THREAD

**Issue by baroquedub** [kmkolasinski/AwesomeBump#66]
Using both the downloadable binary and a compiled version (using QT) I find that the program fails to load with the following error:

'Fatal Error: Sorry but it seems that your graphics card does not support openGL 4.0. Program will not run'

I'm using the source in AwesomeBumpv3.1.4 for Win7/8 x32 (AwesomeBump-Winx32v3.1.4.zip)

I've checked my OpenGL version and I have v3.3 so used the "CONFIG+=release_gl330" command in Additional Arguments for the build steps details. 

Why is it trying to use 4.0?

**Comment by kmkolasinski** [comment]
Do you have the same version of GL in log.txt in both cases. We have still problems with 3.3 sometimes it works sometimes not. Currently we rewriting the part of code responsible by GL context changind deprecated functions with new one. Lets hope this will help. 
I assume you tried the GL330 binary.

**Comment by baroquedub** [comment]
Yes both show the following:
[18/11/2015 12:09:44] {Debug} 		 Starting application:
[18/11/2015 12:09:44] {Debug} 		 "Running the AwesomeBump Pi (2015)"
[18/11/2015 12:09:44] {Debug} 		 Checking OpenGL version...
[18/11/2015 12:09:44] {Debug} 		 Widget OpenGL:  3 . 3
[18/11/2015 12:09:44] {Debug} 		 Context valid:  true
[18/11/2015 12:09:44] {Debug} 		 OpenGL information: 
[18/11/2015 12:09:44] {Debug} 		 VENDOR:  NVIDIA Corporation
[18/11/2015 12:09:44] {Debug} 		 RENDERER:  Quadro FX 1700/PCIe/SSE2
[18/11/2015 12:09:44] {Debug} 		 VERSION:  3.3.0
[18/11/2015 12:09:44] {Debug} 		 GLSL VERSION:  3.30 NVIDIA via Cg compiler
[18/11/2015 12:09:44] {Debug} 		 Version: 3.3
[18/11/2015 12:09:45] {Debug} 		 Error: AwesomeBump does not support openGL versions lower than 4.0 :(

Which is the GL330 binary? I've tried https://github.com/kmkolasinski/AwesomeBump/releases/download/Winx32v3.1.4/AwesomeBump3.14.exe


Thanks

**Comment by CodePhase** [comment]
Could you try the latest source code?  You can get it in zip format from https://github.com/kmkolasinski/AwesomeBump/archive/master.zip

**Comment by kmkolasinski** [comment]
Ok, I had a similar problem if I well remember, there is an if statement in main.cpp
https://github.com/kmkolasinski/AwesomeBump/blob/master/Sources/main.cpp#L144

You can try to force checkOpenGL() in main.cpp to return true.

**Comment by baroquedub** [comment]
Hi both,thanks for your help with this...

@CodePhase 
Tried that latest source code but got the following errors when trying to compile:
J:\_BLENDER Projects\_TOOLS\AwesomeBump-master\Sources\mainwindow.cpp:-1: error: undefined reference to `GpuInfo::GpuInfo(QGLContext*&)'
J:\_BLENDER Projects\_TOOLS\AwesomeBump-master\Sources\mainwindow.cpp:-1: error: undefined reference to `GpuInfo::getTotalMem()'
J:\_BLENDER Projects\_TOOLS\AwesomeBump-master\Sources\mainwindow.cpp:-1: error: undefined reference to `GpuInfo::getAvailMem()'
J:\_BLENDER Projects\_TOOLS\AwesomeBump-master\Sources\mainwindow.cpp:-1: error: undefined reference to `GpuInfo::~GpuInfo()'
J:\_BLENDER Projects\_TOOLS\AwesomeBump-master\Sources\mainwindow.cpp:-1: error: undefined reference to `GpuInfo::~GpuInfo()'
:-1: error: ./Build\Obj\mainwindow.o: bad reloc address 0x0 in section `.rdata'

Running the older QT so might be worth uninstalling and trying the newer one?

@kmkolasinski  

Did as you suggested and just forced return true regardless of whether the OpenGL version was correctly detected in  main.cpp. (I did this in the AwesomeBumpv4.0 for Win7/8 x32 source as the latest master isn't compiling for me)... result was that the program seemed to open ok (GUI appeared) but then I got this error: 
![nvdia-error](https://cloud.githubusercontent.com/assets/316458/11257595/7e197538-8e4a-11e5-81a4-e23fbdaa26fc.png)
and any attempt at accessing the app just gave me Windows 'ping' sounds. Had to force close in the end

**Comment by kmkolasinski** [comment]
It seems that the gpuinfo class is not added to project, just guessing. See the errors lead to gpuinfo each time.
Regarding the nvidia error, it means that the opengl is detected not correctly :/ Try to add the gpuinfo class to the project and build the lastest code since we removed there few bugs.

**Comment by baroquedub** [comment]
Apologies I'm new to QT and can't seem to add that class.

I'm slightly confused by the fact that the Project files shown in QT are different to the ones in the actual Sources folder:
![ab-project-files](https://cloud.githubusercontent.com/assets/316458/11303979/c5ac6ab4-8f9d-11e5-9a4a-503e09cabe56.png)

Should I be adding all the files missing in Sources?

I've tried going to the Edit tab, right clicking on the project name and selecting 'Add existing' (as per instructions for adding classes to a QT project found on YouTube). First I tried just adding gpuinfo.cpp then adding both gpuinfo.cpp and gpuinfo.h. 

Both times these files do correctly appear in the Project window, and are listed in the AwesomeBump.pro config file (if viewed in the editor), i.e. listed under HEADERS = and SOURCES = but when I go back to the Projects tab, in Run, I see a message telling me that "The .pro file "AwesomeBump.pro" could not be parsed.
![ab-project-parse-error](https://cloud.githubusercontent.com/assets/316458/11304171/a8935a0e-8f9e-11e5-811c-87e5b6194aeb.png)

I tried to build but got lots of warnings and the green Run button remains greyed out:
![image](https://cloud.githubusercontent.com/assets/316458/11304355/9995d71a-8f9f-11e5-89e8-4b24ca79bdbf.png)

Sorry if I'm making newbie errors! Any help much appreciated :)

**Comment by baroquedub** [comment]
Ok, well I thought I might try editing that AwesomeBump.pro file in a text editor, and then loading it in QT. Which worked fine and the project compiled with only warnings. But it crashed in the same way as before ("The NVDIA openGL driver lost connection with the display driver due to exceeding the Windows Time-Out limit and is unable to continue. The application must close") However the log.txt file is much longer this time, suggesting that the program got much further in trying to load.
[log.txt](https://github.com/kmkolasinski/AwesomeBump/files/40288/log.txt)

If I copy the compiled .exe and run it seperatetely from QT (i.e. in an application folder with all the required .dll files I get the same crash.

Am I doing something stupid? Or can I do anything further to help debug this?

**Comment by CodePhase** [comment]
My apologies, I didn't add the gpuinfo class to the .pro QtCreator project file when I created it.  I fixed the issue in commit b1cbec375f3afcbb22e013dba25045a3c234caa7.  Try downloading again.

The "Missing Sources" you're seeing is not really an issue.  The sources list in QtCreator is only showing the .cpp files.  The other files are also important, but are not displayed as sources because they're headers and user interfaces.

I'll have a look at your current paintGL issue.  Have you copied all the resources from the <AB-Sources>\Bin to the directory you have the executable located in?  Also, do you have the latest NVidia drivers installed on your system?

One final observation is that you seem to be running on a 32 bit OS from your comment "Win7/8 x32".  I'm not sure if AB is currently compatible with 32 bit but it might be.  I haven't tried it.

**Comment by baroquedub** [comment]
Thanks for your help with this. I'm running Windows7 64bit. The only reason you saw 32bit is because all the sources for Windows listed under releases seem to be called '32bit' i.e. "AwesomeBumpv4.0 for Win7/8 x32" But I am running a 64bit system. And yes, I have the latest drivers for my NVIDIA Quadro FX 1700 graphics card. I tried the new master, and the same error occurs - same crash and log.txt is generated as attached in my comment above. This occurs not just when running the exe separately but also when run from QT so I assume the problem isn't related to  missing files (?) The program does start but then seems to throw an exception which crashes the NVDIA's OpenGL driver. Do the errors in the log.txt file mean anything to you?

**Comment by CodePhase** [comment]
I'm wondering if the instance of glwidget isn't successfully created.  Usually an error like that occurs when trying to read or write to an invalid object.  Maybe the real clue here is the fact that you needed to disable the GL check to get the software to run.  It seems to me that there is a problem creating GL objects on your system for some reason.  It seems that your card supports OpenGL 3.3 so nothing particularly stands out to me ATM.  Would you be willing to try a test build if I put together a debugging branch for this?  It would probably be a bit unstable but may help us narrow down where your (and probably others') issue is.

**Comment by baroquedub** [comment]
Apologies for the confusion. Since using the master branch from 4 days ago and running the latest version of QT, I've been able to compile without having to bypass OpenGL detection. So the program does now run as release_gl330 without me having to force checkOpenGL() to return true in main.cpp. 

So I'm running the latest master branch, without any modifications, but it crashes as explained above.

Would it help you guys if I opened a new issue called 'NVDIA Quadro FX 1700 GLWidget crash'  (and close this one) as I'm now seemingly getting past the initial OpenGL detection ?

I've no problem trying a debugging branch if it helps work out what the problem is.

Thanks again for all your help :)

**Comment by kmkolasinski** [comment]
Hi, sorry for late answer but did you try to build the clean-legacy branch?
This branch does not work correctly so far, but I've managed to replace there some of the deprecated classes with new one.  If you will have still the same problem it means that changing all those deprecated classes was a waste of time... and the problem is somewhere else.

**Comment by baroquedub** [comment]
Similarly, my apologies for the delay. Been tied up with other things. Just tried the clean-legacy branch and got a similar crash - on this build the app never actually opens. As before, lots of error windows are spawned, all saying "The NVDIA openGL driver lost connection with the display driver due to exceeding the Windows Time-Out limit and is unable to continue. The application must close" but now it's QT Creator which crashes.

What a shame! This looks like such a great project. Let me know if I can do any further testing to help you guys out. I'd obviously love to get this working but am also happy to be a guinea pig if you need someone to try different builds.

**Comment by kmkolasinski** [comment]
Ok, so it seems that removing deprecated classes does not solve the problem :/ 
One more question do you have the same problem what here #44  ? (read last few posts)

**Comment by baroquedub** [comment]
That did it! Thank you so much for all your help and support. Very much appreciated.

So now that it opens... I've got to learn how to use it :)
