### ISSUE TITLE
OpenGL error "INVALID_ENUM" 500 at glClear

### ISSUE THREAD

**Issue by John3** [kmkolasinski/AwesomeBump#69]
Hi,
Just starting use AB, Yes I can run AB, just to show you me log, I'm running from a laptop, here is my log I see a few errors. 

http://pastebin.com/7HMZM5Qq

**Comment by kmkolasinski** [comment]
Does it work for you or not? I see that there is a problem with shaders linking: 
```
OpenGL error "INVALID_ENUM" 500 at program->link() called from virtual
```
It also happens sometimes but we also don't understand why there is not log information from GLSL linker.

**Comment by John3** [comment]
I can open AB without problem and use some options... but I not sure it work "correctly" I don't have the time to test it. Just starting with AB =) Give me a few days I will update the Issue. Thanks

**Comment by kmkolasinski** [comment]
Hi, you edited you post, so I didn't receive any mail about that, so I was thinking 
that AB is working on your PC.  Can you send me the log.txt file, from last bug?

**Comment by abulak** [comment]
I'm not sure if I should start a new issue, but this is something I get:

https://gist.github.com/abulak/ccd8901746f4e78b0cc6

black views, and a crash soon;

However, the binary version (4.0) works fine (has usability problems with HIDPI and fonts, but that's a different story)

**Comment by kmkolasinski** [comment]
Hi, the gl330 version does not use tessellation shaders and maybe that is why it work for you. 
Some graphics cards does not want to work with AB, I have no solution for this.

**Comment by kmkolasinski** [comment]
Closing this issue.
