### ISSUE TITLE
Build on OS X 10.11

### ISSUE THREAD

**Issue by theluckyluke** [kmkolasinski/AwesomeBump#74]
I have a MacBook Air (Intel HD 5000, OpenGL 4.1). I tried building 3.0.4, 3.1.4 & 4.0 Linux releases, but none of them worked. I always got a message that my laptop doesn't support the OpenGL version, even with the OpenGL 3.3 settings. Building the master also didn't work, I guess because of #71.

I checked out commit 6ac321331ba9173737a7912536782733f8dd645, the commit before the changes of #71 started. Now everything works :+1:. Thought it's worth sharing, maybe you can add it to the readme or wiki.

**Comment by theluckyluke** [comment]
AwesomeBump starts now, but doesn't show the images or a 3d object. Looks like there are other problems with the OpenGL implementation of OS X or so.

> main.cpp: QGLFormat::CoreProfile disables all OpenGL functions that are depreciated as of OpenGL 3.0

**Comment by kmkolasinski** [comment]
Yeah, we are doing a big mess in the master branch, to be honest it is my fault. However you can always find stable codes in  [releases](https://github.com/kmkolasinski/AwesomeBump/releases) section.

Could you please show as the log file?

**Comment by theluckyluke** [comment]
Here's the log. I don't have time to contribute code, but I can help with testing if possible.

[AwesomeBump.log.txt](https://github.com/kmkolasinski/AwesomeBump/files/101144/AwesomeBump.log.txt)

**Comment by kmkolasinski** [comment]
AwesomeBump file has to executed from the bin folder. Message 
```
Cannot load cube map: check if images listed above exist.
```
means that AB tries to load resources, from certain folder, however it cannot load them because the executable is not located in proper folder.

**Comment by theluckyluke** [comment]
I probably sent you the wrong log file, sorry. I'll try it again when I'm home.

**Comment by theluckyluke** [comment]
This one should be fine. AwesomeBump.app is in the same directory as Configs/ and Core/.

[AwesomeBump.log.txt](https://github.com/kmkolasinski/AwesomeBump/files/101634/AwesomeBump.log.txt)

**Comment by kmkolasinski** [comment]
Do you have possiblity to test it on different GPU, not intel ?

**Comment by theluckyluke** [comment]
No, it only has the Intel card.

**Comment by kmkolasinski** [comment]
So the last thing, did you try with the GL3.3 version? The log file is from normal GL4.0 version. We did not find the way to make AB work on all GPU, the biggest problem is with Intel cards :/

**Comment by theluckyluke** [comment]
Here's the log. It still states 4.1 everywhere.

[AwesomeBump.log.txt](https://github.com/kmkolasinski/AwesomeBump/files/101995/AwesomeBump.log.txt)

**Comment by kmkolasinski** [comment]
Ok, so it is problem with Intel/AB in that case, sorry for that :( you can try older versions since they may work.
