### ISSUE TITLE
Theme problem

### ISSUE THREAD

**Issue by brothermechanic** [kmkolasinski/AwesomeBump#75]
Hello, kmkolasinski
I'm just build AwesomeBump and there is problem with icons and fonts
http://wstaw.org/m/2016/01/26/plasma-desktophO4833.png
As you can see, icons contrast not good, and fonts not as in other apps 
(i opened smplayer for you can see diffence)
It will be useful for me (or may be for other kde users) if you upgrade AwesomeBump theme.
Thank you for this software! I will learn it.

**Comment by kmkolasinski** [comment]
Did you try to use other themes? There is a combo-box with available themes: it is visible on your screen. Your current theme is "windows" you can try other. Change theme, save settings, and restart program.

AB does not use its own theme, but System dependent themes, that is why on each computer it may look differently.

**Comment by brothermechanic** [comment]
The color of AwesomeBump window is system, this is good.
But font is not system. It very badly for read.
My system fonts is Droid Sans 8. 
http://wstaw.org/m/2016/01/26/plasma-desktopwE4833.png
http://wstaw.org/m/2016/01/26/plasma-desktophp4833.png
and all apps used it (gtk apps too)

Icons. AwesomeBump has unical icons, there are no in system theme. But it will be great if you add mode contrast to it. Like bottom 6 icons in left toolbar.

**Comment by kmkolasinski** [comment]
How do you see that font is different? You have Cyrillic font which is hard to compare with Latin alphabet. 
Icons: I think you could help us and create such icons for contrast mode? Since you work in such theme ;) 
I think that the last 6 icons look ok by accident.

**Comment by brothermechanic** [comment]
Hello agane
After update UI (icons) became worse!
http://wstaw.org/m/2016/05/11/plasma-desktopRs4864.png
Now tabs looks without any info (but there is hardly visible icons)
Can you add more contrast to icons, like other ones? Or simply made it white or black? Please

**Comment by ppiecuch** [comment]
I will take a look at icons - I will try to make add to these icons some
white outline - maybe it will be acceptable in light or dark themes.

As for tabs: @kmkolasinski maybe use in tabs icons without letters:
metallic.png instead of showMetallic.png?

Regards
Pawel


On Wed, May 11, 2016 at 3:52 PM, brothermechanic <notifications@github.com>
wrote:

> Hello agane
> After update UI (icons) became worse!
> http://wstaw.org/m/2016/05/11/plasma-desktopRs4864.png
> Now tabs looks without any info (but there is hardly visible icons)
> Can you add more contrast to icons, like other ones? Or simply made it
> white or black? Please
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/kmkolasinski/AwesomeBump/issues/75#issuecomment-218465704>
>



-- 
More:
 >> (http://komsoft.ath.cx/ <http://komsoft.ath.cx/spider.html>)
 >> (http://pawelp.ath.cx/ <http://komsoft.ath.cx/spider.html>)

**Comment by kmkolasinski** [comment]
Hi, thanks for that. I was thinking rather to change all the icons to similar like in "material tab" i.e. with only letters e.g. D - diffusion, S - specular, N - normal map, Mt - metalic.

**Comment by ppiecuch** [comment]
Hi - I will add icons with letters in circle only - showMetallicL.png,
showGroungeL.png etc. I have added some examples in last commit.


P.

On Thu, May 12, 2016 at 8:06 AM, Krzysztof Kolasinski <
notifications@github.com> wrote:

> Hi, thanks for that. I was thinking rather to change all the icons to
> similar like in "material tab" i.e. with only letters e.g. D - diffusion, S
> - specular, N - normal map, Mt - metalic.
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/kmkolasinski/AwesomeBump/issues/75#issuecomment-218668200>
>



-- 
More:
 >> (http://komsoft.ath.cx/ <http://komsoft.ath.cx/spider.html>)
 >> (http://pawelp.ath.cx/ <http://komsoft.ath.cx/spider.html>)

**Comment by kmkolasinski** [comment]
Hi this looks good, but I think the icons prepared by you will not work with dark theme like in @brothermechanic case. At least the area between letter and circle should be filled.

**Comment by kmkolasinski** [comment]
I would resign from symbols everywhere and left just letters.

**Comment by ppiecuch** [comment]
Letters are fine :) but I will try to add some styles to all icons like
this:
[image: Inline image 1]
Maybe it will improve visibility.

P.


On Thu, May 12, 2016 at 7:40 PM, Krzysztof Kolasinski <
notifications@github.com> wrote:

> I would resign from symbols everywhere and left just letters.
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/kmkolasinski/AwesomeBump/issues/75#issuecomment-218831155>
>



-- 
More:
 >> (http://komsoft.ath.cx/ <http://komsoft.ath.cx/spider.html>)
 >> (http://pawelp.ath.cx/ <http://komsoft.ath.cx/spider.html>)

**Comment by ppiecuch** [comment]
Btw - I cannot find these letters - could you post some screenshot?

P.


On Fri, May 13, 2016 at 1:50 PM, Pawel <piecuch.pawel@gmail.com> wrote:

> Letters are fine :) but I will try to add some styles to all icons like
> this:
> [image: Inline image 1]
> Maybe it will improve visibility.
>
> P.
>
>
> On Thu, May 12, 2016 at 7:40 PM, Krzysztof Kolasinski <
> notifications@github.com> wrote:
>
>> I would resign from symbols everywhere and left just letters.
>>
>> —
>> You are receiving this because you commented.
>> Reply to this email directly or view it on GitHub
>> <https://github.com/kmkolasinski/AwesomeBump/issues/75#issuecomment-218831155>
>>
>
>
>
> --
> More:
>  >> (http://komsoft.ath.cx/ <http://komsoft.ath.cx/spider.html>)
>  >> (http://pawelp.ath.cx/ <http://komsoft.ath.cx/spider.html>)
>
>


-- 
More:
 >> (http://komsoft.ath.cx/ <http://komsoft.ath.cx/spider.html>)
 >> (http://pawelp.ath.cx/ <http://komsoft.ath.cx/spider.html>)

**Comment by brothermechanic** [comment]
Thank you!!!
Thank you!!!
Thank you!!!

**Comment by kmkolasinski** [comment]
Which letters? I don't understand. I mean to make icons in a syle of that: [img] (https://github.com/kmkolasinski/AwesomeBump/blob/master/Sources/resources/actions/showGrunge.png) (this is just a proposal). 
I cannot see the picture you have attached.

**Comment by ppiecuch** [comment]
I have added an example of improved icons: diffuse.png diffuseL.png (letter
only) and showDiffuse.png
Could you check if they look fine on dark bg?

Regards
P.


On Fri, May 13, 2016 at 2:02 PM, brothermechanic <notifications@github.com>
wrote:

> Thank you!!!
> Thank you!!!
> Thank you!!!
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/kmkolasinski/AwesomeBump/issues/75#issuecomment-219024617>
>



-- 
More:
 >> (http://komsoft.ath.cx/ <http://komsoft.ath.cx/spider.html>)
 >> (http://pawelp.ath.cx/ <http://komsoft.ath.cx/spider.html>)

**Comment by brothermechanic** [comment]
Cool!
But i can't to compile AB
"RCC: Error in 'content.qrc': Cannot find file 'resources/actions/showDiffuseL.png'"
Please fix that i can to try it.
Thank you

**Comment by ppiecuch** [comment]
Fixed. Thanks.

P.

On Tue, May 17, 2016 at 10:25 PM, brothermechanic <notifications@github.com>
wrote:

> Cool!
> But i can't to compile AB
> "RCC: Error in 'content.qrc': Cannot find file
> 'resources/actions/showDiffuseL.png'"
> Please fix that i can to try it.
> Thank you
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/kmkolasinski/AwesomeBump/issues/75#issuecomment-219842511>
>



-- 
More:
 >> (http://komsoft.ath.cx/ <http://komsoft.ath.cx/spider.html>)
 >> (http://pawelp.ath.cx/ <http://komsoft.ath.cx/spider.html>)

**Comment by brothermechanic** [comment]
There is
http://wstaw.org/m/2016/05/18/plasma-desktopIv4251.png
What you say?

**Comment by ppiecuch** [comment]
Better - I will prepare rest of the icons today and let's see the final
effect.

P.


On Wed, May 18, 2016 at 8:20 AM, brothermechanic <notifications@github.com>
wrote:

> There is
> http://wstaw.org/m/2016/05/18/plasma-desktopIv4251.png
> What you say?
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/kmkolasinski/AwesomeBump/issues/75#issuecomment-219935346>
>



-- 
More:
 >> (http://komsoft.ath.cx/ <http://komsoft.ath.cx/spider.html>)
 >> (http://pawelp.ath.cx/ <http://komsoft.ath.cx/spider.html>)

**Comment by kmkolasinski** [comment]
Hi,
could you check last commit ? Pawel pushed new incons.

**Comment by ppiecuch** [comment]
Not all of them - I have cleaned up non-toolbar ones. Main icons are still in preparation.

P.

**Comment by brothermechanic** [comment]
Hello
I'm just trying to compile AB and get this error
```
Reading /var/tmp/portage/media-gfx/AwesomeBump-9999-r2/work/AwesomeBump-9999/Sources/utils/QtnProperty/Core/Core.pro
Project ERROR: Unknown module(s) in QT: quick
```
https://bpaste.net/show/579e7c216b40

**Comment by kmkolasinski** [comment]
Sorry for late answer. AB does not use any quick tool as far as I remember.... did you solve your problem?
@ppiecuch  how are you doing with icons ? :)

**Comment by brothermechanic** [comment]
No
I have this build error, and cant to finish compilation.

**Comment by brothermechanic** [comment]
Hello
I make update to qt-5.6 and kde5.6
Now AB compiled fine
This is it http://i.imgur.com/viBVvbA.png
breese theme http://i.imgur.com/ETGEDy0.png COOOOL!!!!!
THANK YOU!!! ppiecuch , kmkolasinski 
There is small issues anyway, look on white font on blue value's lines. Can you invert font's color? or create an option for it?
This is what i mean in other qt app (dolphin) http://i.imgur.com/QAUVzk2.png - the fonts is mutch better than in AB

**Comment by kmkolasinski** [comment]
Hi, nice theme and congratulations that you have solved your problem :) 
regarding your problem, you mean the text where the value bars (gray rectangles) are drawn? 

```
Can AB ise system font for gui?
```
This is definitely related to the Qt library possibilities, I think yes it can be done, but I need to google this problem.

**Comment by brothermechanic** [comment]
Thank you
Yes, i mean font on value bars

**Comment by brothermechanic** [comment]
Hello
How about font settings for AB interface?

**Comment by kmkolasinski** [comment]
I removed them because after integration with QtnProperty the font size scrollbar stopped to work...  I couldn't find the problem hence I resigned from this feature.

**Comment by kmkolasinski** [comment]
Ok, I have managed to make font size working and slider bar font color also. There will be a global gui.ini file in the Configs folder in which you will be able to change font settings. I'm not going to play with font styles.

**Comment by kmkolasinski** [comment]
Closing it. An old issue.
