### ISSUE TITLE
Has anybody managed to load a texture?

### ISSUE THREAD

**Issue by xl8r** [kmkolasinski/AwesomeBump#77]
Downloaded. Installed. Clicked Ctrl + O. Got an Open File dialog. Chose a file. Nothing happened, still the same cube hovering above a town square. Has anybody actually managed to get this thing to work?

**Comment by DaOnlyOwner** [comment]
Under the preview tab click "Enable preview".
Then you can see a normal map texture. Adjust it. 
If you think it fits your needs, click Convert N H. 
Now you will see a cube with your texture applied. 
HF ;)

**Comment by kmkolasinski** [comment]
Does to instruction of @DaOnlyOwner  work for you?

**Comment by xl8r** [comment]
Thank you, @DaOnlyOwner. No luck though. The program knows something has been loaded into it since it assigns the input file's name to the output files, but nothing changes in the preview, and the output after blind N H conversion is seven identical files, a white square inside a black square.

I'm afraid it doesn't, @kmkolasinski

**Comment by kmkolasinski** [comment]
So it would be nice to see the log.txt file and example screen of what you have, it is hard to deduce from brief description.

**Comment by popifrex** [comment]
I figured how to make it work, you have to assign the .exe to work with your dedicated gpu not intel's gpu. It worked at least for me.

**Comment by kmkolasinski** [comment]
Ok, thanks for info, glad you solved your problem by yourself. 
Many of you have problem with intel graphics, there is even a huge issue about that. Anyway thanks for info. I'm closing this issue.
