### ISSUE TITLE
Big color banding problem

### ISSUE THREAD

**Issue by brothermechanic** [kmkolasinski/AwesomeBump#79]
This image illustrated the problem
http://i.imgur.com/ufIPnCg.jpg
Is this a bug? Or i do something wrong?
Can you add noise option to blur operation? (this sometimes fix this issue)

**Comment by kmkolasinski** [comment]
Noise - that is a great idea! Yes, that is float precision related bug, if you convert from height to normal it leads to such artifacts. I had plans to work with this but currently we try to add QtnProperty into AB which takes a lot of time.

**Comment by kmkolasinski** [comment]
Sorry I mean from normal to height.

**Comment by brothermechanic** [comment]
Thank's for answer!
It will be great!
Now i found a workaround as 4x image from AB > gimp > 16bit > blur > 0.25x >  export to tiff.

**Comment by kmkolasinski** [comment]
Ok, I will leave this issue open to make me remember about this problem.

**Comment by kmkolasinski** [comment]
I could not find a nice solution for this problem, but I've added noise scroll bar to "recalculate from normal" settings. This helps a little bit for textures like you presented.
