### ISSUE TITLE
You will add PBR support ?

### ISSUE THREAD

**Issue by Hevedy** [kmkolasinski/AwesomeBump#8]
- Metal & Roughness maps support ?  
For example like this: http://www.allegorithmic.com/products/bitmap2material

**Comment by kmkolasinski** [comment]
Good question :) Currently I'am working on 2.0 version where there are no plans for adding PRB functionality, but maybe in 3.0 version... The biggest problem is that I am not familiar with the concept of the PRB, so I will have to learn it, understand and implement, I think the first two will take me most of time.
If you have good sources with well explained texts about PRB, calculation Metal & Roughness maps, etc., it would be nice to read them. 
Regards,
KK

**Comment by Hevedy** [comment]
Nice, your project now is awesome bat with that will be more awesome :+1:   
About PBR i don't have and idea about convert images to maps but i have some things like that:  
https://docs.unrealengine.com/latest/INT/Engine/Rendering/Materials/PhysicallyBased/index.html  
Look at the bottom of the web have some references / docs  
http://seblagarde.wordpress.com/2011/08/17/feeding-a-physical-based-lighting-mode/  
http://seblagarde.wordpress.com/2011/08/17/hello-world/  
http://seblagarde.wordpress.com/2012/04/30/dontnod-specular-and-glossiness-chart/  
http://www.marmoset.co/toolbag/learn/pbr-practice  

I'm not idea if this will help you.
Thanks!

**Comment by kmkolasinski** [comment]
Ok, thank you I will look at them in a free time :)
Best,
KK

**Comment by Hevedy** [comment]
Looks like this is done :+1:

**Comment by kmkolasinski** [comment]
Yeah, problems solved :)
