### ISSUE TITLE
Compilation error on Fedora 23

### ISSUE THREAD

**Issue by Calinou** [kmkolasinski/AwesomeBump#82]
Using commit https://github.com/kmkolasinski/AwesomeBump/commit/bbfacefa6d41dabbf9019bc0c6e6fb3b50b2b879, and trying to compile AwesomeBump on Fedora 23 x86_64 gives me this, after using `cmake . && make`:

```
[  2%] Automatic moc and uic for target awesomebump
[  2%] Built target awesomebump_automoc
[  5%] Building CXX object CMakeFiles/awesomebump.dir/Sources/utils/Mesh.cpp.o
In file included from /home/hugo/Git/awesomebump/Sources/utils/Mesh.hpp:14:0,
                 from /home/hugo/Git/awesomebump/Sources/utils/Mesh.cpp:6:
/home/hugo/Git/awesomebump/Sources/utils/../CommonObjects.h:10:44: fatal error: properties/ImageProperties.peg.h: No such file or directory
 #include "properties/ImageProperties.peg.h"
                                            ^
compilation terminated.
CMakeFiles/awesomebump.dir/build.make:179: recipe for target 'CMakeFiles/awesomebump.dir/Sources/utils/Mesh.cpp.o' failed
make[2]: *** [CMakeFiles/awesomebump.dir/Sources/utils/Mesh.cpp.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/awesomebump.dir/all' failed
make[1]: *** [CMakeFiles/awesomebump.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

```

I do have `qt5-qtbase-devel` and `qt5-qtscript-devel` installed, and I have initialized and updated submodules.

**Comment by kmkolasinski** [comment]
Hi, this version is still under scratch. We slowly migrating GUI to use QtnProperty project. 
I think you forgot to add submodule QtnProperty to AB project., am I correct?

**Comment by CodePhase** [comment]
Also, the cmake build system is pretty far out of date.  I haven't updated it since the QtnProperty effort.  You'd probably have better luck compiling at commit f6ac321331ba9173737a7912536782733f8dd645.

**Comment by kmkolasinski** [comment]
@CodePhase yeah, recently I'm very busy, so I have no time for AB, but as soon I will finish migration I will ask you to prepare cmake :) ok?

**Comment by CodePhase** [comment]
yep, it's something I've been meaning to catch up on :-)

**Comment by kmkolasinski** [comment]
Hi, could you prepare a cmake for current master code? This version is almost ready for release.

**Comment by kmkolasinski** [comment]
@CodePhase is there a chance that you will find time to make a cmake script for AB ? :)
