### ISSUE TITLE
build error on windows

### ISSUE THREAD

**Issue by daxbo** [kmkolasinski/AwesomeBump#83]
Hi there, i tried to build the AB release 4.0 (AwesomeBump-Winx32v4.0), using the latest qtcreator 3.6.1, (w qt5.6.0 - miniGW 32bit)
But i get a couple of errors:

- D:\AwesomeBump-Winx32v4.0\Sources\glwidget.cpp:-1:`
- Fehler: undefined reference to `_imp__glGetError@0'
- D:\AwesomeBump-Winx32v4.0\Sources\main.cpp:-1: Fehler: undefined reference to `_imp__glGetError@0'
- D:\AwesomeBump-Winx32v4.0\Sources\main.cpp:-1: Fehler: undefined reference to `_imp__glGetString@4'
- :-1: Fehler: ./release\main.o: bad reloc address 0x4 in section `.text.startup'
- collect2.exe:-1: Fehler: error: ld returned 1 exit status

Could someone tell me what i do wrong?
I would like to modify (or try to) the AB Code a litle for my needs. 
But first i wann't to build a functional version.
I work on a mobile device with intelGMA and GeForce8400M Chipset (Optimus tech).

Regards

**Comment by DaOnlyOwner** [comment]
I had exactly the same error. You have to use the same compiler that was originally used to compile. 
Am 21.03.2016 11:34 schrieb daxbo <notifications@github.com>:Hi there, i tried to build the AB release 4.0 (AwesomeBump-Winx32v4.0), using the latest qtcreator 3.6.1, (w qt5.6.0 - miniGW 32bit)
But i get a couple of errors:


D:\AwesomeBump-Winx32v4.0\Sources\glwidget.cpp`
Fehler: undefined reference to `_imp__glGetError@0'
D:\AwesomeBump-Winx32v4.0\Sources\main.cpp Fehler: undefined reference to `_imp__glGetError@0'
D:\AwesomeBump-Winx32v4.0\Sources\main.cpp Fehler: undefined reference to `_imp__glGetString@4'

 Fehler: ./release\main.o: bad reloc address 0x4 in section `.text.startup'
collect2.exe Fehler: error: ld returned 1 exit status


Could someone tell me what i do wrong?
I would like to modify (or try to) the AB Code a litle for my needs. 
But first i wann't to build a functional version.
I work on a mobile device with intelGMA and GeForce8400M Chipset (Optimus tech).

Regards

**Comment by daxbo** [comment]
perfect, installed 5.4.2 - and sucesfully compiled!
thanks alot

**Comment by kmkolasinski** [comment]
Great thanks @DaOnlyOwner !
