### ISSUE TITLE
Roughness and Metallic Maps do not show properly

### ISSUE THREAD

**Issue by STHGM** [kmkolasinski/AwesomeBump#84]
For some reason the metallic and roughness values will not update correctly on the 3D preview, they just kept the logo image within. Also I can`t see changes in 3D preview when I modify their values, but I see results on the 2D preview. What might be the problem? The first image shows the 3D view with the issue and 2D view with altered values from the roughness as shown on the left tab. The second image shows the issue even on "Enable Preview" on Diffuse. I'll be posting the log file too if it's needed.
![image](https://cloud.githubusercontent.com/assets/13001726/13946646/94521830-eff4-11e5-99dd-14b56c39f23e.png)
![image](https://cloud.githubusercontent.com/assets/13001726/13946672/c1fed156-eff4-11e5-8f2e-69239b35490b.png)
[log.txt](https://github.com/kmkolasinski/AwesomeBump/files/183804/log.txt)

**Comment by kmkolasinski** [comment]
I see some strange errors in your log: like problem with only one shader linking... but you have intel graphics card which explains a lot... 
Ok, after you convert your diffuse image to rest textures you can disable "Enable preview", it is better to work with that. Did you click "convert to all"?  or did you try "Replot all"? What are the rest of the textures? I see only two.

**Comment by STHGM** [comment]
The other textures seem to be working fine and update correctly, its only the roughness and metallic that are not updating in 3D preview. Tried Replot all and still the same thing. Couldn't find "convert all". I thought it could be something with the material tab, but then I applied a completely white texture but the problem persists. Can it be because I'm using Windows 10? Because remember having no problems on Windows 8.1.

**Comment by kmkolasinski** [comment]
Yes, it may be related to win10, I had a few mails from other people which reported a problem with Win10. But each time I asked to check something I did not received any message... It should work if you compile it with Qt on win10, or maybe just if you replace all the Qt libraries from win8 by win10 libraries.

**Comment by STHGM** [comment]
I'm still quite a noob with GitHub and compiling things from source. Thou everytime I tried to compile it from source it gave me error, usually "Did you forget to git submodule init/update" and typed that on GitShell on the source folder, but still nothing. I tried to follow the pdf on how to build, but was unsuccessful. Am I doing something wrong or forgot something? If its possible, could you make a video on how to compile (as you said some things have changed from the last video)? Also I've been trying to follow this thread: https://github.com/kmkolasinski/AwesomeBump/issues/71
Thanks for your response.

**Comment by kmkolasinski** [comment]
Hi, try the stable release from the link:
https://github.com/kmkolasinski/AwesomeBump/archive/Winx32v4.0.zip
You can find all the versions here:
https://github.com/kmkolasinski/AwesomeBump/releases

**Comment by kmkolasinski** [comment]
Closing due to lack of feedback.
