### ISSUE TITLE
Download latest master in binary form

### ISSUE THREAD

**Issue by Krakean** [kmkolasinski/AwesomeBump#88]
Hello.
Where I can download current master in binary form for Win x64 (nightly builds)?
If there is none, can somebody please compile and upload it somewhere?

**Comment by kmkolasinski** [comment]
Hi, 
You mean that link?: https://github.com/kmkolasinski/AwesomeBump/releases

**Comment by Krakean** [comment]
This link contains too old build (from May 17 2015), I need binaries of current master (7 April 2016)

**Comment by kmkolasinski** [comment]
Current build is under tests so and since May no significant work was done till today.

**Comment by kmkolasinski** [comment]
In a few  days I will prepare current master in a binary form.
