### ISSUE TITLE
Issues compiling

### ISSUE THREAD

**Issue by jimbodigital** [kmkolasinski/AwesomeBump#89]
**first issue**
/Users/myname/Downloads/AwesomeBump-master/build-AwesomeBump-Desktop_Qt_5_6_0_clang_64bit-Release/Build/Ui/ui_mainwindow.h:384: error: no member named 'setElideMode' in 'QStackedWidget'
        tabWidget->setElideMode(Qt::ElideMiddle);
        ~~~~~~~~~  ^
/Users/myname/Downloads/AwesomeBump-master/Sources/mainwindow.cpp:3: In file included from ../Sources/mainwindow.cpp:3:

**and second issue**
/Users/myname/Downloads/AwesomeBump-master/Sources/propertiestree.peg.h:4: error: 'Core/PropertyCore.h' file not found
#include <Core/PropertyCore.h>
         ^

OS X 10.10.5 I would appreciate any help

**Comment by kmkolasinski** [comment]
Hi, please compile one of stable releases from: https://github.com/kmkolasinski/AwesomeBump/releases

**Comment by jimbodigital** [comment]
It builds it now, but won't open. When run from QT says fatal error, when from directories it quits unexpectedly.

**Comment by kmkolasinski** [comment]
What about log file? Is there something which can explain your problem?

**Comment by kmkolasinski** [comment]
Closing, due to lack of feedback.
