### ISSUE TITLE
QT shader

### ISSUE THREAD

**Issue by kostekk** [kmkolasinski/AwesomeBump#9]
Witam, to mój pierwszy post, nie wiem czy w dobrym miejscu założyłem.
Mam problem z QT, od razu mówię że nie jestem dobry w te klocki. Gdy próbuję odpalić projekt (sześcian wirujący wokół własnej osi) na komputerze kolegi wszystko działa poprawnie, po próbie odpalenia go u mnie zamiast grafiki pojawia się biały kwadrat na czarnym tle. Dodam że projekty w 2D przenoszone w ten sam sposób działają poprawnie. Co może być przyczyną?
W Application Output wyskakuje to:

Starting D:\qt_moje\qt1\debug\qt1.exe...
QGLFormat reports profile: none.
GL Vendor    : Intel
GL Renderer  : Intel(R) HD Graphics
GL Version   : 3.1.0 - Build 9.17.10.3517
GL Version   : 3.1
GLSL Version : 1.40 - Intel Build 9.17.10.3517
 Location | Name
------------------------------------------------
shader compilation failed!
Shader log: 
ERROR: 0:3: 'layout' : symbol is deprecated in Forward Compatibile context 
ERROR: 0:3: 'layout' : syntax error syntax error

D:\qt_moje\qt1\debug\qt1.exe exited with code 0

Z góry dziękuję za pomoc!

**Comment by kmkolasinski** [comment]
Cześć,
wszystko wskazuje na to, że to twoja karta graficzna: Intel(R) HD Graphics. 
Zgodnie z wymaganiami AB musi ona obsługiwac wersję minimum 4.0. Tak, czy siak to nie może być intel. 
Przykłady Qt działają bo one nie używają nowych funkcji z języka GLSL to jest ograniczają się do profilu 3.1. Dlatego Ci działa. 
PS: Własnie do mnie dotarło, że ty nie pytasz o AwesomeBump. Ale i tak podejrzewam karte graficzną? Czy twój komputer/laptop nie ma przypadkiem podwójnego układu graficznego np. NVIDIA/Intel (pytam o technologie Optimus)?
