### ISSUE TITLE
AwesomeBump stopped working with latest AMD drivers.

### ISSUE THREAD

**Issue by metaphorset** [kmkolasinski/AwesomeBump#90]
After installing the latest AMD drivers AwesomeBump shows an empty Texture and a single plane in 3D view. Loading Textures work (without changes in the texture view area) but AwesomeBump crashes when clicking on "convert N to H".

**Comment by kmkolasinski** [comment]
As you noticed something is wrong in new drivers that crash AB. Could you show me the log.txt file?

**Comment by metaphorset** [comment]
I've done some testing with both the OpenGL 3.3 and the non GL version version. The latter won't crash and it also shows the texture panel as expected. But it nearly freezes the System for several seconds after I hit "convert N to H"
I'll attach both resulting logs, just in case...

[AwesomeBumpGL330_log.txt](https://github.com/kmkolasinski/AwesomeBump/files/229913/AwesomeBumpGL330_log.txt)
[AwesomeBump_log.txt](https://github.com/kmkolasinski/AwesomeBump/files/229931/AwesomeBump_log.txt)

**Comment by kmkolasinski** [comment]
Hi, I see where is the problem, there is a bug in 4.0 version, current source code does not contain this bug, but it is still not ready to use.  You can try to use 3.14 version until new version will be released.
However I'm not sure if 3.14 version has the same problem.

**Comment by metaphorset** [comment]
Hi, thanks for taking a look into it. 3.14 seems to work so far, I can live with that for the moment. Any Idea when the new version is going to be released?

**Comment by kmkolasinski** [comment]
Hard to say, it really depends how other things will go. We are trying to solve other problem with save/load function in a new GUI, but it goes veeeery slowly. Then if this problem will be solved I'm going to clean the code a little bit and fix other problems which should be easier to do.

**Comment by kmkolasinski** [comment]
It may take from few weeks to months.

**Comment by deranjer** [comment]
Are the build instructions up to date?  I have the same issue and the build instructions don't work either.  It seems to be some sort of issue with building peg.cpp files from pef files?

**Comment by kmkolasinski** [comment]
Yes the instructions are not up to date for a while. You need to pull qtnproperty submodule and then compile it and then compile AB :) We will make it more user friendly soon :)

**Comment by kmkolasinski** [comment]
Closing this issue, because we are going to prepare final release of 5.0 version.
