### ISSUE TITLE
master build issues

### ISSUE THREAD

**Issue by brothermechanic** [kmkolasinski/AwesomeBump#91]
Hello
I get mail about new thunk updates with QtnProperty, and start to build new AB.
This is errors
>CMake Error at CMakeLists.txt:73 Cannot find source file: Sources/formbasemapconversionlevels.cpp
>CMake Error at CMakeLists.txt:73 Cannot find source file: Sources/resources/icon.icns
>./CommonObjects.h:10:44: fatal error: properties/ImageProperties.peg.h: No sutch file
It will be cool to try new version of AB
because in old release is some GL glitch on Linux sometimes.

**Comment by ppiecuch** [comment]
Hi - cmake build has not been updated for some time - maybe try qmake
instead? I will try to update cmake later.

Regards
Pawel


On Thu, May 5, 2016 at 2:39 PM, brothermechanic <notifications@github.com>
wrote:

> Hello
> I get mail about new thunk updates with QtnProperty, and start to build
> new AB.
> This is errors
>
> CMake Error at CMakeLists.txt:73 Cannot find source file:
> Sources/formbasemapconversionlevels.cpp
> CMake Error at CMakeLists.txt:73 Cannot find source file:
> Sources/resources/icon.icns
> ./CommonObjects.h:10:44: fatal error: properties/ImageProperties.peg.h: No
> sutch file
> It will be cool to try new version of AB
> because in old release is some GL glitch on Linux sometimes.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/kmkolasinski/AwesomeBump/issues/91>
>



-- 
More:
 >> (http://komsoft.ath.cx/ <http://komsoft.ath.cx/spider.html>)
 >> (http://pawelp.ath.cx/ <http://komsoft.ath.cx/spider.html>)

**Comment by kmkolasinski** [comment]
Hi, it seems that the cmake is outdated. This file `/formbasemapconversionlevels.cpp` does not exists anymore. Compilation with Qt Creator should work.
First of all you have to pull submodule to main repository. As far as I remember it should be something like that:
git submodule init
git submodule pull
Then check if there are files in the Source/utils/QtnProperty folder. The QtnProperty has to be compiled firstly. 
In future we will make AB instalation more easier.

**Comment by brothermechanic** [comment]
Thanks
Can you please to show me an algorithm
when i did
$  cd AwesomeBump
$ qmake
$ make
i get this error
make[1]: QtnPEG: Command not found

**Comment by kmkolasinski** [comment]
Here is my way:
git clone https://github.com/kmkolasinski/AwesomeBump.git
cd AwesomeBump/Sources/
git submodule update
Then I open Qt Creator and compile QtnProperty and then AwesomeBump. QtnPEG is created after QtnProperty project compilation. This is a tool which is used to generated some files used by AB later.

**Comment by brothermechanic** [comment]
Ok, i try this latter
It will be mutch useful to build with cmake or qmake from cli terminal only ( for gentoo's packages instalation)

**Comment by kmkolasinski** [comment]
Hi,  it seems that there is no cmake file for QtnProperty project, that means for now the only solution is to use qmake or qtDesigner.

**Comment by ppiecuch** [comment]
Rigggght - including Qtn is quite easy (it is just one Unity build file)
but I have to add pef generator targets. Will do this soon.

P.



On Fri, May 6, 2016 at 10:34 PM, Krzysztof Kolasinski <
notifications@github.com> wrote:

> Hi, it seems that there is no cmake file for QtnProperty project, that
> means for now the only solution is to use qmake or qtDesigner.
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/kmkolasinski/AwesomeBump/issues/91#issuecomment-217551400>
>



-- 
More:
 >> (http://komsoft.ath.cx/ <http://komsoft.ath.cx/spider.html>)
 >> (http://pawelp.ath.cx/ <http://komsoft.ath.cx/spider.html>)

**Comment by kmkolasinski** [comment]
Thanks a lot, it would be useful to have simplified build instruction.

**Comment by brothermechanic** [comment]
Ok!
I'm fitally susses compiled AB!
For first look it became better)
Great lens flares!)))
How about color banding hack?

**Comment by kmkolasinski** [comment]
Hi, great to hear that.
Could you remind me what is "color banding hack" ?

**Comment by brothermechanic** [comment]
Cool
The hack: to fix color banding issue you can add noise filter to texture generation process
This is my problem
http://wstaw.org/m/2016/05/11/logo-n.jpg
Look at this terrible gradient steps)))
Hope you can fix that!
Thank you

**Comment by kmkolasinski** [comment]
I've added a possibility to add noise to the texture. It is hidden in the height tab, under conversion from normal to height settings. There is a slider with which you can try to increase the noise in order to hide those steps, then click convert to see the result. 
Then you can add some blur in the normal tab. This should help a bit.

**Comment by brothermechanic** [comment]
Thank you!!!
I will try it

**Comment by kmkolasinski** [comment]
Hi, did you try to use the noise? Does it help?
