### ISSUE TITLE
After startup preview mesh is hidden

### ISSUE THREAD

**Issue by brothermechanic** [kmkolasinski/AwesomeBump#92]
Hello
Small bug.
After AB has start preview mesh is hidden
http://wstaw.org/m/2016/05/11/plasma-desktopsD4864.png
But if i change, for ex push some 3d settings preview mesh is shown agane.

And another bug - Gui style Windows dont changed to Fusion option (restart don't helps)

**Comment by kmkolasinski** [comment]
Hi, thanks for feedback, I will take a look on the bugs you have found.

**Comment by brothermechanic** [comment]
I found a problem
This was because i install a program to system drive as root user
and when i normally run program as normal user AB can't to write config.ini
http://wstaw.org/m/2016/05/11/plasma-desktopFR4864.png
Can you change linux writting path of config.ini to /home/user, may be to /home/user.config/ ?
Thank you

**Comment by kmkolasinski** [comment]
Ok, I will take a look on it.

**Comment by kmkolasinski** [comment]
Well the paths are hardcoded in AB... , why don't you just keep AB in your home folder instead keeping it in the system folder /opt/?

**Comment by brothermechanic** [comment]
It's usefull for several peoples, users of computer

**Comment by kmkolasinski** [comment]
I see one problem: you can have few users with different names, then the settings path should be different for each user. I wonder that there may be a file which points where all the configs should be written (this is not only one file, but also all the files in the `Configs` folder.). I would like to have also current way of working. 
On the other hand you can keep all heavy files in the system folder but you could provide some small bash script that would execute AB in the user home folder and thus all write operations would be done in the user folders. Wouldn't it work?

**Comment by brothermechanic** [comment]
Ok.
Anyway, thank you for this GREAT software!

**Comment by kmkolasinski** [comment]
Ok, I'm closing this issue.
