### ISSUE TITLE
Crash: recursive repaint detected

### ISSUE THREAD

**Issue by pzl** [kmkolasinski/AwesomeBump#94]
Building from source on Linux. build seems successful, but get near-instantaneous crash with the following in log.txt:

```
[27/05/2016 11:47:31] {Debug}        FBOImages::creating new FBO( 1 , 1 ) with id= 53
[27/05/2016 11:47:31] {Debug}        Doing first draw of "diffuse"  texture.
[27/05/2016 11:47:31] {Debug}        MainWindow::Initialization
[27/05/2016 11:47:31] {Warning}      QWidget::repaint: Recursive repaint detected
```

I have tried this building from:
- master
- Linuxv4.0 tag (and zip source download from there)
- Linuxv3.14

I have also tried this with using default openGL version (4.5) and building with OpenGL 3.30 legacy mode (for each version above). Always same results. Build is fine, generates the binary. Running the binary briefly opens a window but closes and crashes in under a second with the log.txt output below. Also included coredump info.

OGL 3.30 full logs: https://gist.github.com/pzl/a7a735bc3250ff9d3ccea6d7a753d268
OGL 4.5 full logs: https://gist.github.com/pzl/d3d53d868d4b4d89d0f4a5e13f08eee5

Note: that if I download the pre-compiled binary, it does run. The language seems to be arabic or something so I can't really use it, but the log.txt for the 4.0 binary is here: https://gist.github.com/pzl/5e3f7ca9778abaf4d5a21db126f8c5bb

**Comment by kmkolasinski** [comment]
Hi, I see in provided log output a warning:
```
Cannot load cube map: check if images listed above exist.
```
which means that you dont run AB from bin folder. In that folder a necessary textures are located, hence the warning.

**Comment by pzl** [comment]
Noted, thank you. Re-ran this from Bin, no more cubemap error in the logs, but did get the same repaint segfault.

[log.txt](https://gist.github.com/pzl/30b79bd75d487366d4a3d19ccebf4da6)

**Comment by kmkolasinski** [comment]
Ok, I don't know where is the problem. Did you tried to build latest code?

**Comment by pzl** [comment]
I was finally able to get master to build and launch. If I launch with `./Bin/AwesomeBump` it will segfault and crash. I had to actually `cd Bin` and then `./AwesomeBump` which I found odd, but that did launch the program without crashing.  How can I launch, install, or call this binary without having to cd to `/usr/bin` or something first?

I'm also now I'm in that situation where it's rendering with a particular font (Akaash, a Bengali font) instead of QT/GTK default. my locale is set to en_US.UTF-8 and default font is set to Liberation Sans. I don't know why this font is being used but it makes everything unusable (I cannot read Bengali). Screenshot attached

![2016-05-31-073101_1480x842_scrot](https://cloud.githubusercontent.com/assets/315796/15672994/fbd0acc6-2701-11e6-803f-924143463c5b.png)

**Comment by kmkolasinski** [comment]
Hi, 
for the first problem you can try to make some bash script which will enter the AB bin folder or you can try to link the executable file with "ln" command. One note, AB has to be located in public folder, if you will put AB into root protected location like "/usr/bin" you need to run AB with root privileges. Otherwise when you will want to save something (especially AB saves some config files) you will encounter several problems. 
For the second question: I need some time, this is a new problem for me and I don't know the answer. You can also help me and google it.

**Comment by pzl** [comment]
Symlinking to the binary doesn't work for me, just crashes.

For what it's worth when I finally get this working I'll be working on the Arch Linux package version for AwesomeBump, so Arch Linux users can use their normal package manager to install AwesomeBump. 

The font issue is probably a my-machine-only problem, so if I can figure out a good way to let the binary be installed in a typical fashion (most things are binaries you can just move right into /usr/bin) I can move forward.

For the short term I'll look at a copying everything into /opt/ and symlinking from /usr/bin maybe. Or running from /opt/ with a bash script in /usr/bin doing the directory changing. For the medium term: would you consider a configurable path to the Configs and textures? Instead of existing where the binary is? Maybe an optional command line flag, which defaults to present behavior when not used (so it doesn't break current usage) but allows for different placement? Or, alternatively, using one of the Qt [standard paths](http://doc.qt.io/qt-5/qstandardpaths.html): DataLocation, ConfigLocation, AppDataLocation, AppConfigLocations. 

Those would allow for more standard installations

**Comment by kmkolasinski** [comment]
Hi, I'm sorry but I have no time to continue the work with AB, I'm going to spend few days to prepare final release of AB. The configurable paths are out of mine plans.
