### ISSUE TITLE
[sub-Sources-make_first-ordered] Error 1 Issue

### ISSUE THREAD

**Issue by DGaste** [kmkolasinski/AwesomeBump#96]
What should I do to fix that?

![issue](https://cloud.githubusercontent.com/assets/20308340/16601365/682bcb5a-430c-11e6-8de2-727bf3c88c53.jpg)

**Comment by kmkolasinski** [comment]
Is this from recent version of source code?

**Comment by DGaste** [comment]
I think so, I downloaded the version from the page yesterday.

**Comment by kmkolasinski** [comment]
Have you solved your problem?
