### ISSUE TITLE
splashscreen and some others

### ISSUE THREAD

**Issue by ppiecuch** [kmkolasinski/AwesomeBump#97]
Hello all
I have committed some small improvments to the code:

1. app. is check for runtime files at startup:

        if (!QFileInfo(resDir+"Configs").isDir() || !QFileInfo(resDir+"Core").isDir()) {
                return QMessageBox::critical(0, "Missing runtime files", QString("Cannot find runtime assets required to run the application (resource path: %1).").arg(resDir));
        }

without runtime files available, application is crash

2. I have added simple splashscreen displaying startup progress. Application startup is now divided into 2 parts: constructor and initializeApp() method:

        MainWindow window;
        QObject::connect(&window,SIGNAL(initProgress(int)),&sp,SLOT(setProgress(int)));
        QObject::connect(&window,SIGNAL(initMessage(const QString&)),&sp,SLOT(setMessage(const QString&)));
        window.initializeApp();

Progress is changed in initializeApp with code like this:

        INIT_PROGRESS(10, "Build image properties");

Regards
Pawel

**Comment by kmkolasinski** [comment]
Hi, thanks for this - cool feature!
Currently I am busy, but in August I will try to make some final release or try to fix some minor issues pointed by other users. 
Krzysztof

**Comment by kmkolasinski** [comment]
Ok, so I have tested it and everything works fine on my PC. This splash screen in awesome !!!
I think it is a time to make a new release version, and this one will be last for me, since I will have no time to continue any work with AB.
I'm closing this issue
