### ISSUE TITLE
AB V.5 error on ubuntu 16.04.1

### ISSUE THREAD

**Issue by Iraito** [kmkolasinski/AwesomeBump#98]
It keeps saying **"error while loading shared libraries: libQt5Script.so.5: cannot open shared object file: No such file or directory"**

**Comment by kmkolasinski** [comment]
Hi, but when (during compilation?) 
The error means that you probably do not have installed proper version of Qt. AB requires 5.X.

**Comment by Iraito** [comment]
I installed it but it still gives me the same error, there's a possibility that i have the wrong package.

**Comment by kmkolasinski** [comment]
I did not check AB on 16.04, I don't know maybe that is the problem. How do you run AB ? From prebuild binary packages ? Or from source code?

**Comment by ldudzic** [comment]
Same here on elementary OS 0.3.2 Freya (built on ubuntu 14.04). I'm using this package: AwesomeBumpV5.Bin64Linux.tar.gz

> ./AwesomeBump: error while loading shared libraries: libQt5Script.so.5: cannot open shared object file: No such file or directory

**Comment by Iraito** [comment]
From prebuild, i will try build a package from sourcecode.

P.S: Will there be a prebuild release of V5.0 for WIN 7/8/10 or will it remain only a build from source option ?

**Comment by kmkolasinski** [comment]
@Iraito  there is a bug in Windows version we have to fix it firstly, I don't know how long will it take, I hope a few days. 

@ldudzic  Do not run AB with direct call `./AwesomeBump` use the shell script which add Qt libraries to your LD_LIBRARY_PATH variable.  Just use `./RunAwesomeBump.sh` or the second one for GL330 version.

**Comment by ldudzic** [comment]
@kmkolasinski I've used it:

> linux:~/Downloads/AwesomeBumpV5.Bin64Linux$ ./RunAwesomeBump.sh
> ./AwesomeBump: error while loading shared libraries: libQt5Script.so.5: cannot open shared object file: No such file or directory

**Comment by kmkolasinski** [comment]
Ok, please try new version of binary package. I've added QtScript.so file to it. Now should work.

**Comment by kmkolasinski** [comment]
@Iraito There is a windows binary package already.

**Comment by ldudzic** [comment]
@kmkolasinski with new build:

> $ ./RunAwesomeBump.sh
> ./RunAwesomeBump.sh: 3: export: (1): bad variable name

**Comment by kmkolasinski** [comment]
I'm worry that 5000x5000 texture is to large for processing, if you have super good GPU it should work, but for standard ones this requires to much memory. Try to work with smaller textures firstly. 

There is   libQt5Script.so.5.4.0 file in AwesomeBump folder, could you try to change its name from:  libQt5Script.so.5.4.0 to  libQt5Script.so.5 ?

**Comment by ldudzic** [comment]
Wow, that was too easy ;) It's ok now and 5000x5000px works pretty good. It's painfully slow but without crashing app. I have GTX 770 (2GB). I'm wondering why this is happening on Windows and not Linux (same hardware)? And last question, isn't there any chance to use CPU for big textures? I use sometimes CPU for heavy lifting in Blender, it's slower but with 16gb RAM.

**Comment by kmkolasinski** [comment]
Thanks for feedback, I'm glad it is working for you now. You can try the following trick 
1. Load 5000x5000 image.
2. Resize it using settings tab to smaller size: from now you can work on smaller image and then at the end resize it back to 5000x5000 without loss of information. This will work unless you use `"Convert"` button or `"Recalculate from..."` etc.

3. Finally in the Settings tab you can try to switch of images which are not used by you, by unchecking the `"Enable images"` buttons

Additionally, you should work with input mode for occlusion texture set to `"Current image"` otherwise AB will compute occlusion texture each time you change something in height or normal texture.  

Regarding the CPU computations, unfortunately this is not possible with AB. Everything is written using GPU approach. This would require rewriting whole code.

**Comment by ldudzic** [comment]
Clicking on `"Resize image" `or hitting shortcut do nothing. 

Unchecked images do the trick, I'm ususally using only diffuse, normal and height.

Decreasing windows size gives me around 100mb free GPU memory.

If you need any brand, graphic, web help I could reach you over email. Thank for your great work!

**Comment by kmkolasinski** [comment]
What do you mean?
``
Clicking on "Resize image"or hitting shortcut do nothing.
``

Regarding
``
If you need any brand, graphic, web help I could reach you over email. Thank for your great work!
``
Thanks :) I need a person who will prepare for me a new video tutorial for version 5.0 ;P

**Comment by kmkolasinski** [comment]
PS: Regarding your problem on windows

``
Windows version works fine but I'm having issue with big texures. I've tried 5000x5000px and diffuse map is loading ok, but normal preview is black and "convert to n h" crash app.
``

As far as I remember on windows there is something which blocks to long GPU computations. This can be changed somewhere in the system configs. I had similar problem on windows last year. 
For example see this [post](https://support.allegorithmic.com/documentation/display/SPDOC/GPU+drivers+crash+with+long+computations)

**Comment by kmkolasinski** [comment]
PPS: there is another trick which you can try, however this may lead to bad results, I mean you can resign from floating point textures. You can easily change this in the source code in file CommonObjects.h line 25 there is a define which sets the openGL texture type to be used during computations. You can try to change this from
```Cpp
#define TEXTURE_FORMAT GL_RGB16F
```
to e.g.
```Cpp
#define TEXTURE_FORMAT GL_RGB
```
or to one from this table: **ftp://ftp.sgi.com/opengl/contrib/blythe/advanced99/notes/node51.html**
But you must compile the source code by yourself.

**Comment by kmkolasinski** [comment]
@ldudzic May I close this issue or you want to discuss here later ?

**Comment by liloven** [comment]
Try This: 

`sudo apt-get install libqt5script5 ibqt5scripttools5 libqt5test5`

**Comment by RulloCH** [comment]
Hello. In my case AB v5.0 opens but the 3d field and the texture field are completely empty and if I try to open an image to work on it there is no response from the program
