### ISSUE TITLE
Help building on mac 10.10

### ISSUE THREAD

**Issue by Waelwindows** [kmkolasinski/AwesomeBump#99]
i can't build with qt creator. i have the following error
error: [AwesomeBump/Sources/properties/Filter3DDOF.peg.cpp] Trace/BPT trap: 5

**Comment by kmkolasinski** [comment]
Hi, try to use `unixBuildScript.sh` script, this guy should works also on OSX system. 
@ppiecuch  will it work ? :)

**Comment by kmkolasinski** [comment]
`unixBuildScript.sh` on linux this script does all the job for you. BTW: I don't know what it the current status of OXS support.

**Comment by Waelwindows** [comment]
i can't use unixBuildScript.sh. this is what it does after i do sh unixBuildScript.sh

`ls: /Users/USERNAME/Downloads/AwesomeBump-master/Sources/utils/QtnProperty: No such file or directory
Initializing QtnProperty module
/Users/USERNAME/Documents/AwesomeBump/unixBuildScript.sh: line 32: cd: /Users/USERNAME/Downloads/AwesomeBump-master/Sources/utils/QtnProperty: No such file or directory
/Users/USERNAME/Documents/AwesomeBump/unixBuildScript.sh: line 34: wget: command not found
unzip:  cannot find or open master.zip, master.zip.zip or master.zip.ZIP.
rm: master.zip: No such file or directory
mv: rename QtnProperty-master/* to ./*: No such file or directory
rm: QtnProperty-master: No such file or directory
Usage: qmake [mode] [options] [files]

QMake has two modes, one mode for generating project files based on
some heuristics, and the other for generating makefiles. Normally you
shouldn't need to specify a mode, as makefile generation is the default
mode for qmake, but you may use this to test qmake on an existing project

Mode:
  -project       Put qmake into project file generation mode
                 In this mode qmake interprets files as files to
                 be built,
                 defaults to *; *; *; *.ts; *.xlf; *.qrc
                 Note: The created .pro file probably will 
                 need to be edited. For example add the QT variable to 
                 specify what modules are required.
  -makefile      Put qmake into makefile generation mode (default)
                 In this mode qmake interprets files as project files to
                 be processed, if skipped qmake will try to find a project
                 file in your current working directory

Warnings Options:
  -Wnone         Turn off all warnings; specific ones may be re-enabled by
                 later -W options
  -Wall          Turn on all warnings
  -Wparser       Turn on parser warnings
  -Wlogic        Turn on logic warnings (on by default)
  -Wdeprecated   Turn on deprecation warnings (on by default)

Options:
   * You can place any variable assignment in options and it will be     *
   * processed as if it was in [files]. These assignments will be parsed *
   * before [files].                                                     *
  -o file        Write output to file
  -d             Increase debug level
  -t templ       Overrides TEMPLATE as templ
  -tp prefix     Overrides TEMPLATE so that prefix is prefixed into the value
  -help          This help
  -v             Version information
  -after         All variable assignments after this will be
                 parsed after [files]
  -norecursive   Don't do a recursive search
  -recursive     Do a recursive search
  -set <prop> <value> Set persistent property
  -unset <prop>  Unset persistent property
  -query <prop>  Query persistent property. Show all if <prop> is empty.
  -qtconf file   Use file instead of looking for qt.conf
  -cache file    Use file as cache           [makefile mode only]
  -spec spec     Use spec as QMAKESPEC       [makefile mode only]
  -nocache       Don't use a cache file      [makefile mode only]
  -nodepend      Don't generate dependencies [makefile mode only]
  -nomoc         Don't generate moc targets  [makefile mode only]
  -nopwd         Don't look for files in pwd [project mode only]
`

**Comment by ppiecuch** [comment]
Hello  - I would wait for mac build - it still does not work (at least on my mac). It still takes me a few weeks to get back to the project and cleanup the build.

Regards
P.

**Comment by kmkolasinski** [comment]
@ppiecuch at least we can try to build it. 
 @Waelwindows  for some script cannot enter the  /Users/USERNAME/Downloads/AwesomeBump-master/Sources/utils/QtnProperty directory ? Could you check the paths, there is a command in the script which tries to enter QtnProperty folder
```bash
cd Sources/utils/QtnProperty
```
but this operation results with errors:
```bash
/Users/USERNAME/Documents/AwesomeBump/unixBuildScript.sh: line 32: cd: /Users/USERNAME/Downloads/AwesomeBump-master/Sources/utils/QtnProperty: No such file or directory
``` 
Additionally you have to find the alternative for `wget` command in osx (this command downloads the content of the url). You have this error:

```
/Users/USERNAME/Documents/AwesomeBump/unixBuildScript.sh: line 34: wget: command not found
```
See this [link](http://stackoverflow.com/questions/4572153/os-x-equivalent-of-linuxs-wget)

Then there is a bunch of error which are related with previous problems.

**Comment by Waelwindows** [comment]
i managed to get it to compile using the v4 code in your release section. however i then discovered my cpu is limited at 3.30 OpenGL which means i can't use AB 😦 , anyways il try to use it on my windows computer when i get back

**Comment by kmkolasinski** [comment]
Well the gl330 requires a special treatment. You have to add "CONFIG+=gl330" to the cmake command lin, however 330 is partially supported which means it sometimes work sometimes not depending on the machine.
